/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4b378d9179d398256da3333be75d3d34)
interface __BaseEnv_Env {
	CACHE: KVNamespace;
	UPLOADS: R2Bucket;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
	DATABASE_URL: string;
	AUTH_SECRET: string;
	R2_ACCOUNT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_BUCKET_NAME: string;
	R2_PUBLIC_URL: string;
	TOKEN_VALUE: string;
	WEBSOCKET_ROOM: DurableObjectNamespace<import("./worker/index").WebSocketRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "WebSocketRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
