/**
 * Generated indexes for the skills under `.agents/skills/`.
 *
 * Two shapes, because the two skills are shaped differently:
 *
 *   - A **categorized rule index** for `supabase-postgres-best-practices`,
 *     whose rules are one file per rule named `<category>-<rule>.md` across
 *     eight categories declared in `references/_sections.md`.
 *   - A **flat file index** for `supabase`, which has a `references/` file and
 *     an `assets/` template but no categories — and whose `assets/` file is
 *     referenced from nowhere in `SKILL.md`, so it is invisible without one.
 *
 * Both are spliced into the skill's `SKILL.md` between HTML-comment markers and
 * rebuilt by `npm run skill:index` (see `build-skill-index.mjs`). Each has a
 * test in `src/test/skill-index.test.ts` asserting the committed file already
 * matches, so a file added, renamed or retitled without regenerating fails a
 * test rather than staying unfindable.
 *
 * Plain ESM with no imports, like `runbook-contents.mjs`, so the plain `node`
 * script and the Vite/Vitest tests can both use it unchanged.
 */

export const INDEX_START = "<!-- rule-index:start — generated by `npm run skill:index`; do not edit by hand -->";
export const INDEX_END = "<!-- rule-index:end -->";

export const FILE_INDEX_START = "<!-- file-index:start — generated by `npm run skill:index`; do not edit by hand -->";
export const FILE_INDEX_END = "<!-- file-index:end -->";

/** `name.md` → the prefix before the first hyphen, which is its category. */
export function prefixOf(fileName) {
  return fileName.replace(/\.md$/, "").split("-")[0];
}

/** A `[` or `]` in a title would end the link label early. */
function linkLabel(text) {
  return text.replace(/[[\]]/g, "\\$&");
}

/**
 * The categories declared as `## N. Name (prefix)` in `_sections.md`, in the
 * order that file lists them (which is its priority order).
 */
export function parseCategories(sectionsSource) {
  return sectionsSource
    .split(/\r?\n/)
    .map((line) => /^##\s+\d+\.\s+(.+?)\s*\(([a-z]+)\)\s*$/.exec(line))
    .filter((match) => match !== null)
    .map((match) => ({ name: match[1], prefix: match[2] }));
}

/**
 * The `title:` from a rule file's YAML front-matter, falling back to the file
 * name so a rule can never be dropped from the index for want of a title.
 */
export function titleOf(fileName, content) {
  const match = /^title:\s*(.+?)\s*$/m.exec(content ?? "");
  return match ? match[1].replace(/^["']|["']$/g, "") : fileName.replace(/\.md$/, "");
}

/**
 * The `impact:` from a rule file's front-matter (`CRITICAL`, `HIGH`, …), or
 * `null` when it has none. The skill ranks its categories by impact, and the
 * rules are what that ranking is for: an agent scanning the index should be able
 * to pick the CRITICAL rules without opening thirty-one files.
 *
 * `impactDescription` (the sibling key) does not match, since the `:` must
 * follow `impact` directly.
 */
export function impactOf(content) {
  const match = /^impact:\s*(.+?)\s*$/m.exec(content ?? "");
  return match ? match[1].replace(/^["']|["']$/g, "") : null;
}

/**
 * A file's own first `# ` heading, or a readable form of its name. Used by the
 * flat index, whose files (`references/skill-feedback.md`, an assets template)
 * carry no front-matter to title them.
 */
export function headingTitleOf(fileName, content) {
  const match = /^#\s+(.+?)\s*$/m.exec(content ?? "");
  if (match) return match[1];
  const stem = fileName.replace(/\.md$/, "").replace(/[-_]+/g, " ");
  return stem.charAt(0).toUpperCase() + stem.slice(1);
}

/**
 * The impact ladder, most important first — the order `_contributing.md`'s
 * "Impact Level Guidelines" table lists. `renderIndex` sorts each category's
 * rules by this rank, so the CRITICAL rules lead every section instead of
 * whatever the alphabet puts there.
 */
export const IMPACT_ORDER = ["CRITICAL", "HIGH", "MEDIUM-HIGH", "MEDIUM", "LOW-MEDIUM", "LOW"];

/**
 * A rule's position in `IMPACT_ORDER`. Anything unranked — a missing `impact:`
 * or a value not in the ladder — sorts *after* every ranked rule rather than
 * counting as zero, so a new level can never masquerade as the most important.
 */
export function impactRank(impact) {
  const rank = IMPACT_ORDER.indexOf((impact ?? "").toUpperCase());
  return rank === -1 ? IMPACT_ORDER.length : rank;
}

/** Most impactful first; file name breaks ties so the order stays stable. */
function byImpactThenName(a, b) {
  return impactRank(a.impact) - impactRank(b.impact) || a.fileName.localeCompare(b.fileName);
}

/** The shared shape: a start marker, blank-separated `### groups` of links, an end marker. */
function renderGroups(start, end, groups) {
  const lines = [start];
  for (const group of groups) {
    lines.push("", `### ${group.heading}`, "");
    for (const entry of group.entries) {
      const note = entry.note ? ` — ${entry.note}` : "";
      lines.push(`- [${linkLabel(entry.title)}](${entry.path})${note}`);
    }
  }
  lines.push("", end);
  return lines.join("\n");
}

/**
 * The categorized index: one `### Name (prefix)` heading per declared category
 * and a link to every rule under it, ordered by impact rank (CRITICAL first)
 * with the file name as the tiebreak. Rules whose prefix is not a declared
 * category are collected under a trailing "Uncategorised" heading rather than
 * silently dropped — `skill-categories.test.ts` is what makes that group a
 * failure, but the index still shows them.
 *
 * `rules` is `{ fileName, title }[]`; the caller reads the files.
 */
export function renderIndex(categories, rules) {
  const sorted = [...rules].sort(byImpactThenName);
  const declared = new Set(categories.map((category) => category.prefix));

  const groups = categories.map((category) => ({
    heading: `${category.name} (${category.prefix})`,
    entries: sorted
      .filter((rule) => prefixOf(rule.fileName) === category.prefix)
      .map((rule) => ({ title: rule.title, path: `references/${rule.fileName}`, note: rule.impact })),
  }));

  const uncategorised = sorted.filter((rule) => !declared.has(prefixOf(rule.fileName)));
  if (uncategorised.length > 0) {
    groups.push({
      heading: "Uncategorised (no matching section in _sections.md)",
      entries: uncategorised.map((rule) => ({ title: rule.title, path: `references/${rule.fileName}`, note: rule.impact })),
    });
  }

  return renderGroups(INDEX_START, INDEX_END, groups);
}

/**
 * The flat index: one heading per directory, a link to every file under it.
 * `groups` is `{ heading, entries: { title, path }[] }[]`.
 */
export function renderFileIndex(groups) {
  return renderGroups(FILE_INDEX_START, FILE_INDEX_END, groups);
}

/**
 * Replace the block between `start` and `end` in `source`, or — when the markers
 * are absent — bootstrap by inserting the block just below the `heading` line.
 * Preserves the file's line endings.
 */
function spliceBlock(source, block, { start, end, heading }) {
  const newline = source.includes("\r\n") ? "\r\n" : "\n";
  const lines = source.split(/\r?\n/);

  const startAt = lines.findIndex((line) => line.startsWith(start));
  const endAt = lines.findIndex((line) => line.startsWith(end));

  let from;
  let to;
  let insert = block.split("\n");
  if (startAt !== -1 && endAt > startAt) {
    from = startAt;
    to = endAt + 1;
  } else {
    const at = lines.findIndex((line) => line.trim() === heading);
    if (at === -1) throw new Error(`Cannot place the index: no markers and no "${heading}" heading.`);
    from = lines[at + 1]?.trim() === "" ? at + 2 : at + 1;
    to = from;
    // Keep a blank line between the inserted block and whatever followed the heading.
    insert = [...insert, ""];
  }

  const out = [...lines.slice(0, from), ...insert, ...lines.slice(to)].join(newline);
  return out.endsWith(newline) ? out : out + newline;
}

/**
 * The skill source with its generated index block replaced. Markers win if they
 * are present; otherwise bootstrap a categorized skill by replacing the fenced
 * block after the "Read individual rule files" paragraph (the hand-written
 * example list the index supersedes).
 */
export function applyIndex(source, indexBlock) {
  const newline = source.includes("\r\n") ? "\r\n" : "\n";
  const lines = source.split(/\r?\n/);

  const startAt = lines.findIndex((line) => line.startsWith(INDEX_START));
  const endAt = lines.findIndex((line) => line.startsWith(INDEX_END));
  if (startAt !== -1 && endAt > startAt) {
    return finish([...lines.slice(0, startAt), ...indexBlock.split("\n"), ...lines.slice(endAt + 1)], newline);
  }

  const anchor = lines.findIndex((line) => line.includes("Read individual rule files"));
  if (anchor === -1) {
    throw new Error('Cannot place the rule index: no markers and no "Read individual rule files" line.');
  }
  const from = lines.findIndex((line, index) => index > anchor && line.trim() === "```");
  if (from === -1) throw new Error("Found no opening ``` fence after the \"Read individual rule files\" line.");
  const to = lines.findIndex((line, index) => index > from && line.trim() === "```");
  if (to === -1) throw new Error("Found no closing ``` fence for the example list.");
  return finish([...lines.slice(0, from), ...indexBlock.split("\n"), ...lines.slice(to + 1)], newline);
}

/** Join lines with the source's newline and guarantee one trailing newline. */
function finish(lines, newline) {
  const out = lines.join(newline);
  return out.endsWith(newline) ? out : out + newline;
}

/** The flat index applied to a skill, bootstrapping below `## Reference Guides`. */
export function applyFileIndex(source, indexBlock) {
  return spliceBlock(source, indexBlock, {
    start: FILE_INDEX_START,
    end: FILE_INDEX_END,
    heading: "## Reference Guides",
  });
}

/** `renderIndex` + `applyIndex` in one call. */
export function buildIndex(source, categories, rules) {
  return applyIndex(source, renderIndex(categories, rules));
}

/** `renderFileIndex` + `applyFileIndex` in one call. */
export function buildFileIndex(source, groups) {
  return applyFileIndex(source, renderFileIndex(groups));
}
