import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { CLIENT_BUILD_CONFIGS } from "@/test/convention-guards";
import { importClosure } from "../../.freebuff/import-closure.mjs";

import {
  DEFAULT_WATCHES,
  DIFF_BUDGET,
  MANIFEST_FILE,
  STAGE_NAMES,
  STAGE_TABLE,
  familyOwners,
  fallbackContentDir,
  hashFile,
  manifestPath,
  matchesInput,
  ownerClause,
  pin,
  readManifest,
  renderManifest,
  stageDeclarationGaps,
  unifiedDiff,
} from "../../.freebuff/gate-drift.mjs";

/**
 * The drift alarm, pinned on fixtures.
 *
 * `.freebuff/gate-drift.mjs` is the one thing watching the gate machinery itself: it
 * hashes every file the build's verdict is made of — the runner, the stage scripts, the
 * mutation checks and their lock, the redactor, the nightly report, the collect ratchet,
 * the coverage gates, the two vitest configs, the compiler and linter config, and the
 * workflows that run all of it — and fails when one is not the file the checked-in manifest
 * records. That makes its *findings* the contract — a changed file, a
 * file nobody pinned, a pinned file that is gone — and its exit codes the difference
 * between "the gates are the recorded ones" (0), "a gate drifted" (1), and "the alarm
 * could not answer at all" (2). A check that quietly read a missing manifest as a pass
 * would be worse than no check, so the two ways it can fail to run are pinned here beside
 * the three ways it can find drift — and so is a third, because an *empty* pin is the one
 * pass that would disable every gate at once: watch rules that match nothing are refused
 * rather than reported as a clean check over zero files.
 *
 * The fixtures are a throwaway directory of tiny `coverage-*.mjs` files and a manifest
 * generated by the script's own `renderManifest`, so the test moves with the format
 * instead of keeping a second copy of it. `GATE_HASHES_FILE` is the seam that points the
 * alarm at them, the way `MUTATION_LOCK_FILE` points a crash-safety test at its own lock —
 * nothing but a test ever sets it.
 *
 * The last two cases are the ones that matter on a real branch: one runs the alarm against
 * the committed manifest and the real tree, and compares the checked-in file to what
 * `--write` would produce; the other pins the *set* those watch rules resolve to, because a
 * rule that has stopped matching would otherwise shrink the pin silently while every
 * remaining hash still matched. That is what makes the manifest a ratchet rather than a
 * comment: a hand-edit to a gate file, a runner, a workflow or the manifest's watch rules
 * fails here, in the fast suite, before the drift stage has to say it in CI.
 */

const projectRoot = fileURLToPath(new URL("../..", import.meta.url));
const SCRIPT = path.join(projectRoot, ".freebuff", "gate-drift.mjs");

/** The watch rule a fixture manifest records, matching the default. */
const WATCH_PATTERN = "^coverage-.*\\.mjs$";

interface Report {
  mode: string;
  gate: string;
  exitCode: number;
  manifest: string;
  checked: number;
  findings: {
    kind: string;
    path: string;
    detail: string;
    diff?: string;
    /** The watch rule that names the path, or `null` when no rule does. */
    family?: string | null;
    /** The stage that owns that family, as the refusal's clause, or `null` for no family. */
    owner?: string | null;
  }[];
  changed: string[];
  unpinned: string[];
  gone: string[];
  message?: string;
  /** Said when a pass could not keep the text it matched: the diff cache is degraded. */
  warning?: string;
  /** Why that write was refused, and the directory it was writing to. */
  cause?: string;
  /** Where the text that matched the pin was kept, when a pass (or a write) could keep it. */
  stash?: { dir: string; stashed: number; fallback?: string };
  /** The targeted form of `--write`: what it was asked about, and what moved. */
  targets?: string[];
  moved?: { path: string; from: string; to: string }[];
  /** Pinned files that also do not match the tree, which the re-pin did not record. */
  left?: { kind: string; path: string; detail: string }[];
  /** `--status` only: how many files the manifest names, and which a re-pin would record. */
  pinned?: number;
  recordable?: string[];
  /** `--status` only: the diff cache's own health, counted against the pin. */
  cache?: { fresh: number; fallback: number; missing: number; dir: string; fallbackDir: string };
  /** The moved families no stage's key names: what makes a red check a refusal too. */
  refused?: { rule: string; moved: number }[];
  /** That refusal as one sentence, so a consumer reports what the alarm said. */
  refusal?: string;
  /**
   * The moved findings grouped by family, in the order the report prints the headings: the rows
   * beside it are flat, so this is what a consumer folding the report itself follows.
   */
  movedFamilies?: { rule: string; moved: number; owner: string }[];
}

let root: string;
/** Where the tests' runs keep the text they matched, so none of them touches the real one. */
let stashDir: string;
/** Where a run that cannot write `stashDir` falls back to: also a throwaway, for the same reason. */
let fallbackDir: string;

beforeAll(() => {
  root = mkdtempSync(path.join(tmpdir(), "gate-drift-"));
  stashDir = path.join(root, "stash");
  fallbackDir = path.join(root, "stash-fallback");
});

afterAll(() => {
  rmSync(root, { recursive: true, force: true });
});

/** A fresh fixture directory, so one case's files cannot leak into another's. */
function caseDir(): string {
  return mkdtempSync(path.join(root, "case-"));
}

/** The project-relative, forward-slashed key the manifest records for a file. */
function keyOf(file: string): string {
  return path.relative(projectRoot, file).split(path.sep).join("/");
}

/** Run the alarm and read back its stdout, its stderr and its exit code. */
function run(
  args: string[],
  env: Record<string, string> = {},
): { status: number; stdout: string; stderr: string } {
  const result = spawnSync(process.execPath, [SCRIPT, ...args], {
    cwd: projectRoot,
    encoding: "utf8",
    // Every run in this file stashes into a throwaway directory: the stash is a
    // git-ignored convenience, and a test has no business writing the project's own. The
    // fallback is pointed at one too, so no run here writes the machine's real temporary
    // directory — and a case that *wants* the fallback can say so by naming its own.
    env: {
      ...process.env,
      GATE_CONTENT_DIR: stashDir,
      GATE_CONTENT_FALLBACK_DIR: fallbackDir,
      ...env,
    },
  });
  if (result.error) throw result.error;
  return { status: result.status ?? -1, stdout: result.stdout ?? "", stderr: result.stderr ?? "" };
}

/** `--json` against one manifest, parsed: the report and the exit code beside it. */
function check(
  manifest: string,
  env: Record<string, string> = {},
): { status: number; report: Report } {
  const result = run(["--json"], { GATE_HASHES_FILE: manifest, ...env });
  return { status: result.status, report: JSON.parse(result.stdout) as Report };
}

/** `--status`: the one line it answers with, and the exit code beside it. */
function runStatus(
  manifest: string,
  env: Record<string, string> = {},
): { status: number; stdout: string } {
  const result = run(["--status"], { GATE_HASHES_FILE: manifest, ...env });
  return { status: result.status, stdout: result.stdout };
}

/** A targeted `--write`: the arguments, the fixture manifest, the report and the code. */
function repinRun(args: string[], manifest: string): { status: number; report: Report } {
  const result = run([...args, "--json"], { GATE_HASHES_FILE: manifest });
  return { status: result.status, report: JSON.parse(result.stdout) as Report };
}

/** Two pinned fixture scripts, so "only the named one moved" is observable. */
function pairFixture(): { dir: string; manifest: string; alpha: string; beta: string } {
  const dir = caseDir();
  const alpha = path.join(dir, "coverage-alpha.mjs");
  const beta = path.join(dir, "coverage-beta.mjs");
  writeFileSync(alpha, "export const alpha = 1;\n");
  writeFileSync(beta, "export const beta = 2;\n");
  const manifest = path.join(dir, "gate-hashes.mjs");
  pinManifest(manifest, dir, ["coverage-alpha.mjs", "coverage-beta.mjs"]);
  return { dir, manifest, alpha, beta };
}

/** The one watch rule a fixture manifest records, narrowed to the fixture's own files. */
function fixtureWatches(watchDir: string): { dir: string; pattern: string }[] {
  return [{ dir: watchDir, pattern: WATCH_PATTERN }];
}

/** Write a manifest pinning the given names, as the script's own renderer would. */
function pinManifest(manifest: string, watchDir: string, names: string[]): void {
  const files: Record<string, string> = {};
  for (const name of names) {
    const full = path.join(watchDir, name);
    files[keyOf(full)] = hashFile(full);
  }
  writeFileSync(
    manifest,
    renderManifest({ algorithm: "sha1", watches: fixtureWatches(watchDir), files }),
  );
}

/**
 * A fixture tree of pinned `.yml` files, watched by a rule no stage's key can reach.
 *
 * Distinct from `fixture()` on purpose: a throwaway `.mjs` is swept up by the lint stage's whole-tree
 * extension glob, so a family of them has an owner, while a `.yml` under a temporary directory is
 * named by no stage's `inputs` at all — the shape the refusal exists for, and the shape the real
 * tree's workflows rule takes.
 */
function flowFixture(): { dir: string; manifest: string; script: string } {
  const dir = caseDir();
  const script = path.join(dir, "flow-ci.yml");
  writeFileSync(script, "name: ci\n");
  const manifest = path.join(dir, "gate-hashes.mjs");
  writeFileSync(
    manifest,
    renderManifest({
      algorithm: "sha1",
      watches: [{ dir, pattern: "^flow-.*\\.yml$" }],
      files: { [keyOf(script)]: hashFile(script) },
    }),
  );
  return { dir, manifest, script };
}

/** A fixture tree of one pinned script, and the manifest that pins it. */
function fixture(): { dir: string; manifest: string; script: string } {
  const dir = caseDir();
  const script = path.join(dir, "coverage-alpha.mjs");
  writeFileSync(script, "export const alpha = 1;\n");
  const manifest = path.join(dir, "gate-hashes.mjs");
  pinManifest(manifest, dir, ["coverage-alpha.mjs"]);
  return { dir, manifest, script };
}

describe("the gate drift alarm", () => {
  it("passes when every pinned script hashes to what the manifest records", () => {
    const { dir, manifest } = fixture();
    const { status, report } = check(manifest);

    expect(status).toBe(0);
    expect(report.gate).toBe("pass");
    expect(report.exitCode).toBe(0);
    expect(report.checked).toBe(1);
    expect(report.findings).toEqual([]);
    expect(report.changed).toEqual([]);
    // The alarm was pointed at the fixture's manifest, not the project's own: the seam
    // is what keeps this a fixture test and not a read of the real tree.
    expect(report.manifest).toBe(keyOf(path.join(dir, "gate-hashes.mjs")));
    expect(report.manifest).not.toBe(MANIFEST_FILE);
  });

  it("fails when a pinned script on disk is not the one that was pinned", () => {
    const { manifest, script } = fixture();
    // The weakening the alarm exists for: the hash no longer matches, and nothing else
    // in the tree has changed.
    writeFileSync(script, "export const alpha = 1;\n// and quietly do less\n");

    const { status, report } = check(manifest);

    expect(status).toBe(1);
    expect(report.gate).toBe("fail");
    expect(report.changed).toHaveLength(1);
    expect(report.changed[0]).toBe(keyOf(script));
    expect(report.findings).toHaveLength(1);
    expect(report.findings[0].kind).toBe("changed");
    expect(report.findings[0].path).toBe(keyOf(script));
    expect(report.findings[0].detail).toContain("on disk");
    expect(report.findings[0].detail).toContain("pinned");
  });

  it("fails when a watched script is not pinned at all", () => {
    const { dir, manifest } = fixture();
    // A new gate that nobody pinned is exactly as unguarded as a weakened one.
    const added = path.join(dir, "coverage-beta.mjs");
    writeFileSync(added, "export const beta = 2;\n");

    const { status, report } = check(manifest);

    expect(status).toBe(1);
    expect(report.unpinned).toEqual([keyOf(added)]);
    expect(report.findings).toHaveLength(1);
    expect(report.findings[0].kind).toBe("unpinned");
    expect(report.findings[0].detail).toContain("not in the pinned hashes");
  });

  it("reads a suite's copy-for-test copy as debris, not as an unpinned gate", () => {
    const { dir, manifest } = fixture();
    // The convention the mutation suites use: a pinned script copied beside itself under a
    // test's name — present only while the suite runs, gone when the case ends. While it is
    // here it matches the watch rule, but it is nobody's gate; reading it as an unpinned one
    // made every concurrent check report drift that the suite's own cleanup erased.
    writeFileSync(path.join(dir, "coverage-alpha.copy-for-test.mjs"), "export const alpha = 1;\n");
    writeFileSync(path.join(dir, "coverage-alpha.preflight-copy.mjs"), "export const alpha = 1;\n");

    const { status, report } = check(manifest);

    expect(status).toBe(0);
    expect(report.gate).toBe("pass");
    expect(report.unpinned).toEqual([]);
    expect(report.findings).toEqual([]);
  });

  it("still reports a genuinely new gate file a copy's name does not cover", () => {
    const { dir, manifest } = fixture();
    // The ignore is a suffix on a copy's name, not a licence: a file that is not wearing one
    // is exactly as unpinned as before, debris beside it or not.
    writeFileSync(path.join(dir, "coverage-alpha.copy-for-test.mjs"), "export const alpha = 1;\n");
    const added = path.join(dir, "coverage-beta.mjs");
    writeFileSync(added, "export const beta = 2;\n");

    const { status, report } = check(manifest);

    expect(status).toBe(1);
    expect(report.unpinned).toEqual([keyOf(added)]);
    expect(report.findings).toHaveLength(1);
    expect(report.findings[0].path).toBe(keyOf(added));
  });

  it("answers --status clean while a suite's copy sits beside the pin", () => {
    const { dir, manifest } = fixture();
    writeFileSync(path.join(dir, "coverage-alpha.copy-for-test.mjs"), "export const alpha = 1;\n");

    const { status, stdout } = runStatus(manifest);

    expect(status).toBe(0);
    expect(stdout).toContain("all match");
  });

  it("fails when a pinned script is gone", () => {
    const { manifest, script } = fixture();
    rmSync(script);

    const { status, report } = check(manifest);

    expect(status).toBe(1);
    expect(report.gone).toEqual([keyOf(script)]);
    expect(report.findings).toHaveLength(1);
    expect(report.findings[0].kind).toBe("gone");
  });

  it("reports every kind of drift in one run, ordered changed, unpinned, gone", () => {
    const { dir, manifest, script } = fixture();
    const gone = path.join(dir, "coverage-gamma.mjs");
    writeFileSync(gone, "export const gamma = 3;\n");
    pinManifest(manifest, dir, ["coverage-alpha.mjs", "coverage-gamma.mjs"]);

    writeFileSync(script, "export const alpha = 99;\n");
    writeFileSync(path.join(dir, "coverage-beta.mjs"), "export const beta = 2;\n");
    rmSync(gone);

    const { status, report } = check(manifest);

    expect(status).toBe(1);
    expect(report.findings.map((item) => item.kind)).toEqual(["changed", "unpinned", "gone"]);
    expect(report.changed).toEqual([keyOf(script)]);
    expect(report.unpinned).toEqual([keyOf(path.join(dir, "coverage-beta.mjs"))]);
    expect(report.gone).toEqual([keyOf(gone)]);
  });

  it("folds the findings under a heading per family, the stage that owns it named there", () => {
    // The alarm's own diff has to carry the repair the runner's family fold does: which watch rule
    // names the files, and which stage should own that family. The fixture's files live in a throwaway
    // directory no *scoped* input declares, so the honest owner here is the lint stage — whose
    // whole-tree `**/*.mjs` sweep keys every `.mjs` file there is — which is the same fallback the
    // real tree's `collect-*` family gets. A recorded path the rule no longer names belongs to no
    // family at all, and is said rather than guessed.
    const { dir, manifest, script } = fixture();
    // A recorded path no rule names any more: pinned, then removed, so the alarm has a finding whose
    // path belongs to no family at all — the one shape that carries no rule and no repair.
    const legacy = path.join(dir, "legacy.mjs");
    writeFileSync(legacy, "export const legacy = 1;\n");
    pinManifest(manifest, dir, ["coverage-alpha.mjs", "legacy.mjs"]);
    rmSync(legacy);
    // …then the weapon: the pinned script is the drifted one, so it is the family's moved member.
    writeFileSync(script, "export const alpha = 9;\n");

    const { report } = check(manifest);
    const rule = fixtureWatches(dir)[0];
    const label = `${rule.dir}/${rule.pattern}`;

    // One row per finding, in the finding order, each still carrying its family and its repair — the
    // fold is a rendering of the rows and nothing about them is dropped from the JSON.
    expect(report.findings.map((item) => item.kind)).toEqual(["changed", "gone"]);
    expect(report.findings.map((item) => item.family)).toEqual([label, null]);
    const [changed, gone] = report.findings;
    expect(changed.owner).toBe(" — held by the lint stage");
    expect(gone.owner).toBeNull();

    // The *order* the headings take travels beside the rows, so a consumer folding the report itself
    // does not have to re-derive which family leads.
    expect(report.movedFamilies).toEqual([
      { rule: label, moved: 1, owner: " — held by the lint stage" },
    ]);

    // …and the human report prints a heading per family with the rows in the order they were
    // collected, then — last — a heading of its own for the pinned path no rule names any more.
    const human = run([], { GATE_HASHES_FILE: manifest }).stdout;
    const lines = human.split("\n");
    const familyAt = lines.indexOf(`  FAMILY  ${label} (1) — held by the lint stage`);
    const unnamedAt = lines.indexOf("  UNNAMED  1 file(s) no watch rule names");
    expect(familyAt).toBeGreaterThanOrEqual(0);
    expect(lines[familyAt + 1]).toContain(`CHANGED  ${keyOf(script)}`);
    expect(unnamedAt).toBeGreaterThan(familyAt);
    expect(lines[unnamedAt + 1]).toContain(`GONE  ${keyOf(legacy)}`);
    // The heading is the statement now; the row no longer repeats it.
    expect(human).not.toContain("           family  ");
  });

  it("orders the family headings by exposure, keeping the finding order inside each one", () => {
    // A red run's summary leads with the families nothing below measures, so the alarm's own fold
    // has to take the same order or a reader comparing the two has to work out which family leads.
    // The fixture puts the two shapes side by side: a `.yml` in a directory no stage's `inputs`
    // reaches — exposed, and so first — beside a family the lint sweep holds whole, whose two moved
    // members then keep the order they were collected in (`changed` before `unpinned`).
    const dir = caseDir();
    const alpha = path.join(dir, "coverage-alpha.mjs");
    const beta = path.join(dir, "coverage-beta.mjs");
    const flow = path.join(dir, "flow-ci.yml");
    writeFileSync(alpha, "export const alpha = 1;\n");
    writeFileSync(beta, "export const beta = 2;\n");
    writeFileSync(flow, "name: ci\n");
    const manifest = path.join(dir, "gate-hashes.mjs");
    const files: Record<string, string> = {
      [keyOf(alpha)]: hashFile(alpha),
      [keyOf(flow)]: hashFile(flow),
    };
    writeFileSync(
      manifest,
      renderManifest({
        algorithm: "sha1",
        watches: [
          ...fixtureWatches(dir),
          { dir, pattern: "^flow-.*\\.yml$" },
        ],
        files,
      }),
    );
    // One drift in each family, and a third file the sweep holds that the pin does not name: the lint
    // family moves twice, the workflows family once and exposed.
    writeFileSync(alpha, "export const alpha = 9;\n");
    writeFileSync(flow, "name: drifted\n");

    const { report } = check(manifest);
    const swept = `${dir}/${WATCH_PATTERN}`;
    const workflows = `${dir}/^flow-.*\\.yml$`;

    // Two rows, exposed family first — and the payload says so in the same order the report prints.
    expect(report.findings.map((item) => item.kind)).toEqual(["changed", "changed", "unpinned"]);
    expect(report.movedFamilies?.map((family) => family.rule)).toEqual([workflows, swept]);
    expect(report.movedFamilies).toEqual([
      { rule: workflows, moved: 1, owner: " — no stage keys it; name it in a stage's `inputs`" },
      { rule: swept, moved: 2, owner: " — held by the lint stage" },
    ]);

    const lines = run([], { GATE_HASHES_FILE: manifest }).stdout.split("\n");
    const exposedAt = lines.indexOf(
      `  FAMILY  ${workflows} (1) — no stage keys it; name it in a stage's \`inputs\``,
    );
    const heldAt = lines.indexOf(`  FAMILY  ${swept} (2) — held by the lint stage`);
    expect(exposedAt).toBeGreaterThanOrEqual(0);
    expect(heldAt).toBeGreaterThan(exposedAt);
    // The rows under a heading sit between it and the next one, in the collected order.
    const rowAt = (row: string) => lines.findIndex((line) => line.trim().startsWith(row));
    expect(rowAt(`CHANGED  ${keyOf(flow)}`)).toBe(exposedAt + 1);
    expect(rowAt(`CHANGED  ${keyOf(alpha)}`)).toBe(heldAt + 1);
    expect(rowAt(`UNPINNED  ${keyOf(beta)}`)).toBeGreaterThan(rowAt(`CHANGED  ${keyOf(alpha)}`));
  });

  it("checks the claims the stage table's own entries make, and the order they are in", () => {
    // The table is the whole stage declaration now — `label`, the gate `script` it runs with the
    // override a test drives that script through, the `inputs` its key covers, and `editsTree` on the
    // three checks that rewrite the working tree — so the claims an entry makes *about the list* are
    // read as one function and refused by the runner (`stageOrderFindings` reports them, and a run
    // will not start on a finding). A claim is only a declaration until its cases can fail for it, so
    // each is asked of a doctored copy of the table: the function takes the list in hand rather than
    // reading the file, which is the only way to watch a claim fire without bending the real one.
    expect(stageDeclarationGaps()).toEqual([]);
    // The four fields the table declares, read back from the rows themselves: a stage a reader is
    // told about is one every report can name.
    for (const stage of STAGE_TABLE) {
      expect(typeof stage.label).toBe("string");
      expect(stage.inputs.length).toBeGreaterThan(0);
    }
    expect(STAGE_NAMES).toEqual(STAGE_TABLE.map((stage) => stage.name));

    /** The real table with one entry's claim broken, so the refusal can be watched firing. */
    const bent = (name: string, changes: Record<string, unknown>) =>
      STAGE_TABLE.map((stage) => (stage.name === name ? { ...stage, ...changes } : stage));

    // A label is what every report calls the stage — the summary line, an annotation's title, the run
    // page — so a missing one is a stage nothing can name…
    expect(stageDeclarationGaps(bent("lint", { label: "" }))).toEqual([
      { stage: "lint", kind: "label", detail: "the lint stage has no label" },
    ]);
    // …and a shared one is two rows nothing can tell apart.
    expect(stageDeclarationGaps(bent("drift", { label: "lint baseline" }))).toEqual([
      {
        stage: "drift",
        kind: "label",
        detail: 'the drift and lint stages are both labelled "lint baseline"',
      },
    ]);
    // A declared script is the gate the stage runs and the stage's own `inputs` are the key its pass
    // is recorded under, so a script behind none of them is the looseness the key exists to catch.
    expect(stageDeclarationGaps(bent("drift", { inputs: [".freebuff/run.md"] }))).toEqual([
      {
        stage: "drift",
        kind: "script",
        detail: "the drift stage runs .freebuff/gate-drift.mjs and none of its own inputs names it",
      },
    ]);
    // A script with no override variable would be a test seam named `undefined`.
    expect(
      stageDeclarationGaps(
        bent("runbook", { script: { env: "", path: "./build-contents.mjs" } }),
      ),
    ).toEqual([
      {
        stage: "runbook",
        kind: "script",
        detail: "the runbook stage's script names no override variable",
      },
    ]);
    // The tree-editing checks rewrite the working tree one file at a time, so they run last: an
    // `editsTree` anywhere else is a stage that runs while another may be holding a mutated file,
    // and a `check` name two of them share would attribute a healed lock to whichever came first.
    expect(stageDeclarationGaps(bent("lint", { editsTree: "guard sweep" }))).toEqual([
      {
        stage: "mutation",
        kind: "editing",
        detail: 'the mutation and lint stages both carry the `check` name "guard sweep"',
      },
      {
        stage: "lint",
        kind: "editing",
        detail:
          "the lint stage edits the tree, so it has to be one of the last 4 (mutation-fifth, mutation-coverage, mutation-preflight, mutation)",
      },
    ]);

    // The shape the runner builds from the table, checked where the alarm can see it: a stage's
    // `editsTree` is the lock `check` name a recovery is attributed by, and the pin's own re-key is
    // never owned (it holds every family whole by construction).
    expect(STAGE_TABLE.filter((stage) => stage.editsTree !== undefined).map((stage) => stage.name)).toEqual(
      ["mutation-coverage", "mutation-preflight", "mutation"],
    );
  });

  it("names the stage that owns a family the runner's way, sweeping only as a fallback", () => {
    // The alarm reads the *runner's* stage list (`STAGE_TABLE`) to name an owner, so the reading that
    // matters is pinned where it is observable: the row shape `familyOwners` takes (`file`, `rule`,
    // `keys`) is recomputed here from the declarations, and each family is held to the stage it
    // settles on. A family whose members a *scoped* stage names is owned by that stage; the lint
    // stage's whole-tree `.mjs` sweep owns a family only where nothing else names a member of it.
    const rowsFor = (rule: string, files: string[]) =>
      files.map((file) => ({
        file,
        rule,
        keys: STAGE_TABLE.filter((stage) =>
          stage.inputs.some((input) => matchesInput(input, file)),
        ).map((stage) => stage.name),
      }));

    const coverageRule = ".freebuff/^coverage-.*\\.mjs$";
    const coverage = rowsFor(coverageRule, [
      ".freebuff/coverage-floor.mjs",
      ".freebuff/coverage-headroom.mjs",
    ]);
    expect(familyOwners(coverage, STAGE_TABLE).get(coverageRule)).toEqual({
      stage: "mutation-coverage",
      via: ".freebuff/coverage-floor.mjs",
      whole: true,
    });

    // A family a scoped stage only part-holds: the stage that names a member is named, and the clause
    // is the refusal's `extend` one.
    const scriptsRule = ".freebuff/^(ci|comment-gate|gate-drift|redact|nightly-report|pr-comment)\\.mjs$";
    const scripts = familyOwners(
      rowsFor(scriptsRule, [".freebuff/ci.mjs", ".freebuff/nightly-report.mjs"]),
      STAGE_TABLE,
    );
    expect(scripts.get(scriptsRule)).toEqual({
      stage: "mutation",
      via: ".freebuff/ci.mjs",
      whole: false,
    });
    expect(ownerClause(scriptsRule, scripts)).toBe(
      " — extend the mutation stage, which already keys .freebuff/ci.mjs",
    );

    // A family nothing but the lint sweep holds: the sweep keeps it, `whole`, rather than the family
    // reading as ownerless while the lint key covers every member.
    const collectRule = ".freebuff/^(collect-.*|.*-collect-baselines)\\.mjs$";
    const collect = familyOwners(
      rowsFor(collectRule, [".freebuff/collect-run.mjs", ".freebuff/collect-gates.mjs"]),
      STAGE_TABLE,
    );
    expect(collect.get(collectRule)).toEqual({
      stage: "lint",
      via: ".freebuff/collect-gates.mjs",
      whole: true,
    });

    // A family no stage names at all is `null` — the fact the refusal's words state — and gets the
    // explicit clause rather than the silence a family the pin does not hold would get.
    const workflowsRule = ".github/workflows/^.*\\.ya?ml$";
    const workflows = familyOwners(rowsFor(workflowsRule, [".github/workflows/ci.yml"]), STAGE_TABLE);
    expect(workflows.get(workflowsRule)).toBeNull();
    expect(ownerClause(workflowsRule, workflows)).toBe(
      " — no stage keys it; name it in a stage's `inputs`",
    );
  });

  it("refuses when a moved family is behind no stage's key, rather than advising a re-pin", () => {
    // The ordinary repair — re-pin the change — is the wrong advice for a family no stage's key
    // names: the re-pin records the new hash and leaves the family measured by nothing, so the next
    // loosening in it is reported as drift and never fails a gate that reads those files. So the
    // check refuses in the coverage refusal's own words, and carries both the list and the sentence.
    const { dir, manifest, script } = flowFixture();
    writeFileSync(script, "name: drifted\n");
    const label = `${dir}/^flow-.*\\.yml$`;

    const { status, report } = check(manifest);
    expect(status).toBe(1);
    expect(report.gate).toBe("fail");
    // The row keeps its family and its ownerless clause — the refusal qualifies the repair, it does
    // not replace the finding.
    expect(report.findings[0].family).toBe(label);
    expect(report.findings[0].owner).toBe(" — no stage keys it; name it in a stage's `inputs`");
    expect(report.refused).toEqual([{ rule: label, moved: 1 }]);
    expect(report.refusal).toBe(
      `1 moved watch family behind no stage's key: ${label} (1 moved). Only the pin's own check ` +
        "re-runs on the next change to any of them — name each in a stage's `inputs` (the stage " +
        "list is in `.freebuff/gate-drift.mjs`), and `npm run gates:status` prints the family view.",
    );

    // The human report prints it last, after the paragraph that says to re-pin, so the ordinary
    // advice is read first and then corrected where it does not apply.
    const human = run([], { GATE_HASHES_FILE: manifest }).stdout;
    expect(human).toContain(`gate-drift: refusal — ${report.refusal}`);
    expect(human.indexOf("re-pin it with `npm run gates:pin`")).toBeLessThan(
      human.indexOf("gate-drift: refusal — "),
    );

    // A moved family a stage *does* key is an ordinary finding: the lint sweep holds every `.mjs`
    // that exists, so the same drift there has an owner and nothing to refuse about.
    const keyed = fixture();
    writeFileSync(keyed.script, "export const alpha = 9;\n");
    const plain = check(keyed.manifest).report;
    expect(plain.refused).toBeUndefined();
    expect(plain.refusal).toBeUndefined();
    expect(plain.findings[0].owner).toBe(" — held by the lint stage");

    // `--status` is one line by contract and keeps it; its `--json` report is the check's whole
    // payload, so a job reads the refusal there rather than parsing the sentence.
    expect(runStatus(manifest).stdout).not.toContain("refusal");
    const asJson = JSON.parse(
      run(["--status", "--json"], { GATE_HASHES_FILE: manifest }).stdout,
    ) as Report;
    expect(asJson.refused).toEqual([{ rule: label, moved: 1 }]);
  });

  it("cannot answer without a manifest, and says so instead of passing", () => {
    const dir = caseDir();
    const missing = path.join(dir, "gate-hashes.mjs");

    const { status, report } = check(missing);

    expect(status).toBe(2);
    expect(report.gate).toBe("fail");
    expect(report.exitCode).toBe(2);
    expect(report.message).toContain("gate-hashes.mjs");
    expect(report.message).toContain("npm run gates:pin");
  });

  it("cannot answer when the manifest does not parse", () => {
    const dir = caseDir();
    const manifest = path.join(dir, "gate-hashes.mjs");
    writeFileSync(manifest, "this is not a module\n");

    const { status, report } = check(manifest);

    expect(status).toBe(2);
    expect(report.message).toContain("could not be read");
  });

  it("names the re-pin command when a gate has drifted", () => {
    const { manifest, script } = fixture();
    writeFileSync(script, "// weakened\n");

    const result = run([], { GATE_HASHES_FILE: manifest });

    expect(result.status).toBe(1);
    expect(result.stdout).toContain("npm run gates:pin");
    expect(result.stdout).toContain("CHANGED");
  });

  it("--write records the tree, and a check then agrees", () => {
    const dir = caseDir();
    for (const [name, body] of [
      ["coverage-alpha.mjs", "export const alpha = 1;\n"],
      ["coverage-beta.mjs", "export const beta = 2;\n"],
    ]) {
      writeFileSync(path.join(dir, name), body);
    }
    const manifest = path.join(dir, "gate-hashes.mjs");
    // The watch rules are recorded in the manifest, so the first `--write` is given one
    // by hand: an absent manifest falls back to the default rules, which are the real
    // tree and not this fixture.
    writeFileSync(
      manifest,
      renderManifest({ algorithm: "sha1", watches: fixtureWatches(dir), files: {} }),
    );

    const written = run(["--write"], { GATE_HASHES_FILE: manifest });
    expect(written.status).toBe(0);
    expect(written.stdout).toContain("pinned 2 gate file(s)");

    const { status, report } = check(manifest);
    expect(status).toBe(0);
    expect(report.checked).toBe(2);

    // The file on disk is exactly what the renderer produces for this tree, which is
    // what lets the committed manifest be compared to it byte for byte.
    expect(readFileSync(manifest, "utf8")).toBe(
      renderManifest({
        algorithm: "sha1",
        watches: fixtureWatches(dir),
        files: {
          [keyOf(path.join(dir, "coverage-alpha.mjs"))]: hashFile(path.join(dir, "coverage-alpha.mjs")),
          [keyOf(path.join(dir, "coverage-beta.mjs"))]: hashFile(path.join(dir, "coverage-beta.mjs")),
        },
      }),
    );
  });

  it("--write repairs an unreadable manifest rather than refusing", () => {
    const { manifest, script } = fixture();
    writeFileSync(manifest, "this is not a module\n");

    const written = run(["--write"], { GATE_HASHES_FILE: manifest });
    expect(written.status).toBe(0);

    // A repaired manifest still needs watch rules; with the module gone it falls back to
    // the defaults, so the repair pins the real gate machinery — the runner and the gate
    // scripts as well as the coverage family — and is then a genuine alarm about the
    // project's own tree rather than the fixture's.
    const repaired = readFileSync(manifest, "utf8");
    expect(repaired).toContain("export const watches = [");
    expect(repaired).toContain(".freebuff/ci.mjs");
    expect(repaired).toContain(".freebuff/coverage-floor.mjs");
    expect(repaired).toContain("vitest.config.ts");
    expect(check(manifest).status).toBe(0);
    expect(hashFile(script)).toHaveLength(40);
  });

  it("refuses a pin that names nothing, so an empty alarm cannot read as a pass", () => {
    // The failure this file exists to prevent, one level up: if the watch rules stop
    // matching, a check over zero files would answer "pass" and every gate below it would
    // go unchecked. The alarm refuses instead.
    const dir = caseDir();
    const manifest = path.join(dir, "gate-hashes.mjs");
    writeFileSync(
      manifest,
      renderManifest({
        algorithm: "sha1",
        watches: [{ dir, pattern: "^nothing-matches-.*\\.mjs$" }],
        files: {},
      }),
    );

    const { status, report } = check(manifest);
    expect(status).toBe(2);
    expect(report.checked).toBe(0);
    expect(report.message).toContain("watches no file");

    // And `--write` refuses to record it rather than writing an empty pin.
    const written = run(["--write"], { GATE_HASHES_FILE: manifest });
    expect(written.status).toBe(2);
  });

  it("cannot answer a manifest that names no watch rule at all", () => {
    const dir = caseDir();
    const manifest = path.join(dir, "gate-hashes.mjs");
    writeFileSync(path.join(dir, "coverage-alpha.mjs"), "export const alpha = 1;\n");
    writeFileSync(
      manifest,
      renderManifest({ algorithm: "sha1", watches: [], files: {} }),
    );

    const { status, report } = check(manifest);
    expect(status).toBe(2);
    expect(report.message).toContain("names no watch rule");
  });

  it("cannot answer a manifest whose watch rule is malformed", () => {
    const dir = caseDir();
    const manifest = path.join(dir, "gate-hashes.mjs");
    writeFileSync(
      manifest,
      "export const algorithm = 'sha1';\nexport const watches = [{ pattern: 7 }];\nexport const files = {};\n",
    );

    const { status, report } = check(manifest);
    expect(status).toBe(2);
    expect(report.message).toContain("malformed watch rule");
  });

  it("reports a watch rule naming a directory that is not there instead of crashing", () => {
    const dir = caseDir();
    const manifest = path.join(dir, "gate-hashes.mjs");
    writeFileSync(
      manifest,
      renderManifest({
        algorithm: "sha1",
        watches: [{ dir: path.join(dir, "gone"), pattern: WATCH_PATTERN }],
        files: {},
      }),
    );

    const { status, report } = check(manifest);
    expect(status).toBe(2);
    expect(report.message).toContain("a watch rule could not be read");
  });

  it("does not pin the manifest itself, even when a watch rule matches it", () => {
    const dir = caseDir();
    // A manifest named like a gate script would otherwise pin its own hash and become
    // impossible to rewrite.
    const manifest = path.join(dir, "coverage-hashes.mjs");
    writeFileSync(path.join(dir, "coverage-alpha.mjs"), "export const alpha = 1;\n");
    writeFileSync(manifest, renderManifest({ algorithm: "sha1", watches: [], files: {} }));

    const pinned = pin([manifest], fixtureWatches(dir));

    expect(Object.keys(pinned)).toEqual([keyOf(path.join(dir, "coverage-alpha.mjs"))]);
  });

  it("pins a file once even when two watch rules both name it", () => {
    const dir = caseDir();
    writeFileSync(path.join(dir, "coverage-alpha.mjs"), "export const alpha = 1;\n");    const pinned = pin([], [
      { dir, pattern: WATCH_PATTERN },
      { dir, pattern: "^coverage-alpha\\.mjs$" },
    ]);

    expect(Object.keys(pinned)).toEqual([keyOf(path.join(dir, "coverage-alpha.mjs"))]);
  });
});

/**
 * The targeted re-pin: `--write <path>`, the one change automation may make to the manifest.
 *
 * `npm run gates:pin` records the whole tree, which is right for a person with a diff to
 * read and wrong for a script that has just written *one* pinned file — run from automation
 * it would bless every other file in that checkout, including one somebody loosened by hand.
 * So the contract here is a permission, two refusals and one report: the named file's hash
 * moves and nothing else does, a file the manifest does not already pin is refused (adding a
 * gate is a person's decision), a pinned file that is gone is refused rather than dropped,
 * and any *other* pinned file that has drifted is **named in `left`** rather than refused — a
 * re-pin for what you wrote must not absorb drift it did not cause, and refusing on top of
 * that bought nothing: the other entry keeps the hash it already had, so the next check
 * reports the drift either way, while the refusal itself blocked the one command a script in
 * a shared checkout needed. Each refusal is checked against the manifest's bytes, not just
 * its exit code: a refusal that had already half-written would be worse than no check — and
 * so is a report that got the untouched entries wrong.
 */
describe("the targeted re-pin", () => {
  it("moves the named entry and leaves every other pin alone", () => {
    const { manifest, alpha, beta } = pairFixture();
    const betaBefore = hashFile(beta);
    writeFileSync(alpha, "export const alpha = 1;\n// and quietly do less\n");

    const { status, report } = repinRun(["--write", keyOf(alpha)], manifest);

    expect(status).toBe(0);
    expect(report.mode).toBe("write");
    expect(report.targets).toEqual([keyOf(alpha)]);
    expect(report.moved).toHaveLength(1);
    expect(report.moved?.[0]).toMatchObject({ path: keyOf(alpha), to: hashFile(alpha) });
    expect(report.moved?.[0].from).toHaveLength(40);
    expect(report.moved?.[0].from).not.toBe(hashFile(alpha));

    const written = readFileSync(manifest, "utf8");
    expect(written).toContain(hashFile(alpha));
    expect(written).toContain(betaBefore);
    // The ratchet still holds afterwards: a check over the fixture agrees.
    expect(check(manifest).status).toBe(0);
  });

  it("is a no-op when the named file already matches, and does not rewrite the file", () => {
    const { manifest, alpha } = pairFixture();
    const before = readFileSync(manifest, "utf8");

    const { status, report } = repinRun(["--write", keyOf(alpha)], manifest);

    expect(status).toBe(0);
    expect(report.moved).toEqual([]);
    expect(readFileSync(manifest, "utf8")).toBe(before);
  });

  it("refuses a path the manifest does not pin, so automation cannot add a gate", () => {
    const { dir, manifest } = pairFixture();
    const added = path.join(dir, "coverage-gamma.mjs");
    writeFileSync(added, "export const gamma = 3;\n");
    const before = readFileSync(manifest, "utf8");

    const { status, report } = repinRun(["--write", keyOf(added)], manifest);

    expect(status).toBe(2);
    expect(report.message).toContain(keyOf(added));
    expect(report.message).toContain("npm run gates:pin");
    expect(readFileSync(manifest, "utf8")).toBe(before);
  });

  it("refuses a pinned file that is gone rather than dropping the pin", () => {
    const { manifest, beta } = pairFixture();
    rmSync(beta);
    const before = readFileSync(manifest, "utf8");

    const { status, report } = repinRun(["--write", keyOf(beta)], manifest);

    expect(status).toBe(2);
    expect(report.message).toContain("will not drop a pin");
    expect(readFileSync(manifest, "utf8")).toBe(before);
  });

  it("re-pins the named file and names the drift it left alone", () => {
    const { manifest, alpha, beta } = pairFixture();
    // The file being re-pinned *and* an unrelated one have both moved. The named one is what
    // the caller asked for; the unrelated one is somebody else's in-flight edit, and the
    // command answers 0 having recorded exactly what it was asked about.
    const betaPinned = hashFile(beta);
    writeFileSync(alpha, "export const alpha = 1;\n// changed\n");
    writeFileSync(beta, "export const beta = 2;\n// loosened by somebody else\n");

    const { status, report } = repinRun(["--write", keyOf(alpha)], manifest);

    expect(status).toBe(0);
    expect(report.moved?.map((row) => row.path)).toEqual([keyOf(alpha)]);
    // The other file is reported, with what is wrong with it — and *only* it, because a
    // `left` that included the file just recorded would read as a re-pin that did nothing.
    expect(report.left).toEqual([
      expect.objectContaining({ kind: "changed", path: keyOf(beta) }),
    ]);
    expect(report.left?.[0]?.detail).toContain("pinned");

    // Nothing was absorbed: the manifest's own bytes are the re-pinned alpha beside beta's
    // *old* entry, so the next check still reports beta exactly as it did before.
    const written = readFileSync(manifest, "utf8");
    expect(written).toContain(`${JSON.stringify(keyOf(beta))}: ${JSON.stringify(betaPinned)}`);
    const after = check(manifest);
    expect(after.status).toBe(1);
    expect(after.report.changed).toEqual([keyOf(beta)]);
  });

  it("says on the log which pinned files it left, and how to record them", () => {
    const { manifest, alpha, beta } = pairFixture();
    writeFileSync(alpha, "export const alpha = 1;\n// changed\n");
    writeFileSync(beta, "export const beta = 2;\n// changed too\n");

    const result = run(["--write", keyOf(alpha)], { GATE_HASHES_FILE: manifest });

    expect(result.status).toBe(0);
    // A person reads this log, and the count is the one number that says whether the manifest
    // describes the checkout: a re-pin that printed only its own row would read as a pinned
    // tree, which is the reading the old refusal existed to force — and it paid for that
    // reading by making the command unusable beside somebody else's edit.
    expect(result.stdout).toContain(`  REPINNED  ${keyOf(alpha)}`);
    expect(result.stdout).toContain(
      `  left: 1 other pinned file(s) do not match the tree and were not recorded —`,
    );
    expect(result.stdout).toContain(`        ${keyOf(beta)} (changed)`);
    expect(result.stdout).toContain("`npm run gates:pin` records the rest.");
  });

  it("refuses to re-pin against a manifest it cannot read", () => {
    const { dir } = pairFixture();
    const missing = path.join(dir, "gate-hashes.mjs");
    rmSync(missing);

    const { status, report } = repinRun(["--write", "coverage-alpha.mjs"], missing);

    expect(status).toBe(2);
    expect(report.message).toContain("does not exist");
  });

  it("refuses a named path without --write instead of quietly checking", () => {
    const { manifest, alpha } = pairFixture();

    const { status, report } = repinRun([keyOf(alpha)], manifest);

    expect(status).toBe(2);
    expect(report.message).toContain("without --write");
  });

  it("keeps the whole-tree --write whole, with no paths named", () => {
    const { manifest, alpha, beta } = pairFixture();
    writeFileSync(alpha, "export const alpha = 9;\n");
    writeFileSync(beta, "export const beta = 9;\n");

    const written = run(["--write"], { GATE_HASHES_FILE: manifest });

    expect(written.status).toBe(0);
    expect(written.stdout).toContain("pinned 2 gate file(s)");
    expect(written.stdout).not.toContain("re-pinned");
    expect(check(manifest).status).toBe(0);
  });
});
/**
 * Reading a drift: the loosening itself, not two hex prefixes.
 *
 * A pin records a hash, which is what makes it small and instant and what makes a drift
 * unreadable — so the text that *matched* the pin is stashed whenever a check passes or the
 * pin is written, and the next drift is shown as a unified diff against it. The stash lives
 * under `.ci/` (git-ignored, like the result cache) and is a convenience, not a gate: the
 * cases here pin both halves of that — that a diff appears when there is text to diff, and
 * that its *absence* is reported as absence rather than turned into a guess.
 *
 * The three properties the diff renderer itself has to keep are pinned apart from the tree,
 * because they are properties of the function: it is capped and says how much it dropped, a
 * change too large to align line by line says so instead of pretending, and every row is
 * redacted the way the runner redacts everything it prints — this text ends up in a public
 * CI log, so a diff that quoted a secret-looking path would be a leak that reads like a
 * feature.
 *
 * `GATE_CONTENT_DIR` is the seam: every run in this file stashes into a temp directory, so a
 * fixture cannot write the project's own, and a case can point a run at its own.
 */
/**
 * Which end of a line a byte follows, and why the pin cannot be made of it.
 *
 * This was the one drift the alarm could report that was not there, and it was silent in the
 * direction that matters. A hash over raw bytes is not reproducible across two checkouts of one
 * blob: `core.autocrlf=true` gives this working tree CRLF and gives the `ubuntu-latest` runner
 * the drift stage actually runs on LF, and git records LF either way. So a pin taken here was a
 * hash the runner could not produce — the drift stage failed in CI on a file nobody had changed,
 * while every local run stayed green, because the checkout kept restoring the very line endings
 * the pin had been taken from. Nothing about the code could tell the two apart, and the two
 * copies of `hashFile`/`hashBytes` were the shape of it: one reading of "a file's hash", written
 * twice, so a change to one of them would have left the pin and the stash disagreeing about the
 * same file.
 *
 * A workflow edit is where it surfaced, and it is worth saying why that file: it was the one
 * file in the pin a CRLF checkout had rewritten, so it was the only one whose re-pin could come
 * out unreproducible. Every other pinned file was already LF and hashed the same either way.
 */
describe("the pin's line endings", () => {
  /** One pinned fixture, written with the line endings the case asks for. */
  function pinned(eol: string): { manifest: string; script: string } {
    const dir = caseDir();
    const script = path.join(dir, "coverage-alpha.mjs");
    const manifest = path.join(dir, "gate-hashes.mjs");
    const lines = ["export const alpha = 1;", "export const beta = 2;", ""];
    writeFileSync(script, lines.join(eol));
    writeFileSync(
      manifest,
      renderManifest({
        algorithm: "sha1",
        watches: fixtureWatches(dir),
        files: { [keyOf(script)]: hashFile(script) },
      }),
    );
    return { manifest, script };
  }

  it("reads the LF bytes a runner checks out as the content a CRLF checkout pinned", () => {
    const { manifest, script } = pinned("\r\n");
    expect(check(manifest).status).toBe(0);

    // The same commit, checked out on ubuntu-latest: git's blob is LF, so the runner's
    // working tree is. This is the run that used to report CHANGED on an untouched file.
    writeFileSync(script, ["export const alpha = 1;", "export const beta = 2;", ""].join("\n"));
    expect(check(manifest).status).toBe(0);

    // And the fold is narrow: content is still what the pin is made of, so a real edit on
    // either side of it is still a drift rather than something the folding absorbed.
    writeFileSync(script, ["export const alpha = 1;", "export const beta = 3;", ""].join("\r\n"));
    expect(check(manifest).status).toBe(1);
  });

  it("leaves a file that has no CRLF hashing as its own bytes", () => {
    // The other forty-nine pins were recorded from an LF tree, so folding has to be a no-op
    // there or this would have re-pinned the whole gate surface to accommodate one file.
    const dir = caseDir();
    const script = path.join(dir, "coverage-alpha.mjs");
    writeFileSync(script, "export const alpha = 1;\n");
    expect(hashFile(script)).toBe(createHash("sha1").update(readFileSync(script)).digest("hex"));
  });
});

describe("reading a drift", () => {
  it("stashes the text a passing check matched, and diffs against it when the file moves", () => {
    const { manifest, script } = fixture();
    expect(check(manifest).status).toBe(0);

    // The weakening the alarm exists for, now shown as the line that changed.
    writeFileSync(script, "export const alpha = 2;\n// and quietly do less\n");

    const { status, report } = check(manifest);
    const diff = report.findings[0].diff ?? "";

    expect(status).toBe(1);
    expect(diff).toContain("--- pinned");
    expect(diff).toContain("+++ on disk");
    expect(diff).toContain("-export const alpha = 1;");
    expect(diff).toContain("+export const alpha = 2;");
    expect(diff).toContain("+// and quietly do less");
    // The hunk header points at the line in the file, not at the top of the trimmed region.
    expect(diff).toContain("@@ -1,1 +1,2 @@");
  });

  it("keeps the stash it has when a check fails, so the diff is still against the pin", () => {
    const { manifest, script } = fixture();
    check(manifest);
    // The loosened text must never become what the next diff calls "pinned".
    writeFileSync(script, "export const alpha = 9;\n");
    check(manifest);

    writeFileSync(script, "export const alpha = 1;\n// drifted again\n");
    const { report } = check(manifest);

    // The diff is against the text the *pin* records, so the line that never changed is
    // context and the loosened line the failed check saw is nowhere in it.
    expect(report.findings[0].diff).toContain(" export const alpha = 1;");
    expect(report.findings[0].diff).toContain("+// drifted again");
    expect(report.findings[0].diff).not.toContain("alpha = 9;");
  });

  it("stashes what --write recorded, so the next drift is read against the new text", () => {
    const { manifest, script } = fixture();
    writeFileSync(script, "export const alpha = 2;\n");
    expect(run(["--write"], { GATE_HASHES_FILE: manifest }).status).toBe(0);

    writeFileSync(script, "export const alpha = 3;\n");
    const { report } = check(manifest);

    expect(report.findings[0].diff).toContain("-export const alpha = 2;");
    expect(report.findings[0].diff).toContain("+export const alpha = 3;");
  });

  it("shows no diff when the matching text was never stashed, and says why", () => {
    const { manifest, script } = fixture();
    writeFileSync(script, "export const alpha = 1;\n// never stashed\n");

    const result = run([], { GATE_HASHES_FILE: manifest });
    expect(result.status).toBe(1);
    expect(result.stdout).toContain("1 changed file(s) have no pinned copy on hand");

    const { report } = check(manifest);
    expect(report.findings[0].kind).toBe("changed");
    expect(report.findings[0].diff).toBeUndefined();
  });

  it("refuses to diff a stashed copy that is not the text the pin records", () => {
    const { dir, manifest } = fixture();
    check(manifest);
    // A stale or hand-edited cache could otherwise describe a change that never happened,
    // which is worse than showing nothing: the cached text is verified against the pin.
    const key = keyOf(path.join(dir, "coverage-alpha.mjs"));
    writeFileSync(path.join(stashDir, encodeURIComponent(key)), "export const alpha = 777;\n");
    writeFileSync(path.join(dir, "coverage-alpha.mjs"), "export const alpha = 2;\n");

    const { report } = check(manifest);

    expect(report.findings[0].diff).toBeUndefined();
  });

  it("caps a large diff and says how much it did not show", () => {
    const before = Array.from({ length: 80 }, (_, index) => `pinned line ${index}`).join("\n");
    const after = Array.from({ length: 80 }, (_, index) => `on disk line ${index}`).join("\n");

    const diff = unifiedDiff(before, after, { path: "fixture.mjs" }) ?? "";

    expect(diff.split("\n").length).toBeLessThanOrEqual(DIFF_BUDGET + 8);
    expect(diff).toContain("more changed line(s) not shown");
  });

  it("says a change is too large to align rather than guessing at one", () => {
    const block = (tag: string) =>
      Array.from({ length: 1200 }, (_, index) => `${tag} ${index}`).join("\n");

    const diff = unifiedDiff(block("pinned"), block("disk"), { path: "fixture.mjs" }) ?? "";

    expect(diff).toContain("too large to align");
    expect(diff.split("\n").length).toBeLessThanOrEqual(DIFF_BUDGET + 8);
  });

  it("redacts the diff, because this text ends up in a public CI log", () => {
    const before = "const alpha = 1;\nconst secrets = read('.env.local');\n";
    const after = "const alpha = 2;\nconst secrets = read('.env.local');\n";

    const diff = unifiedDiff(before, after, { path: "fixture.mjs" }) ?? "";

    expect(diff).toContain("-const alpha = 1;");
    expect(diff).toContain("+");
    expect(diff).not.toContain(".env.local");
    expect(diff).toContain("<redacted>");
  });

  it("is unchanged for a file it can read exactly, so an equal pair has no diff", () => {
    expect(unifiedDiff("same\n", "same\n")).toBeNull();
  });

  it("refuses to stash a matched script that does not balance, so a truncated copy can never become the pin's reference", () => {
    // The stash verifies a copy against the pin by hash, and the hash is blind to the one
    // truncation that *is* the pin: a write cut off early enough can hash to exactly what
    // the manifest recorded, which is the incident this guard closed on the write side —
    // `preview-preflight.mjs` sat truncated at its pinned hash for a day. The diff cache
    // is the other half: a copy stashed from that tree would sit beside the pin as "what
    // the pin recorded" and every later drift for that file would be reviewed against the
    // truncated text. So the same balance check every writer saves through
    // (`.freebuff/whole-write.mjs`) is read here against the bytes about to be kept.
    const { dir, manifest, script } = fixture();
    const truncated = "export function half() {\n  const open = (`";
    writeFileSync(script, truncated);
    // Re-pinned with the truncated text as the pin, because that is the state being held:
    // the hash is honest, the text is not whole.
    expect(run(["--write"], { GATE_HASHES_FILE: manifest }).status).toBe(0);

    // A passing check with the matching (truncated) tree tries to stash it — and must not.
    const passing = run([], { GATE_HASHES_FILE: manifest });
    expect(passing.status).toBe(0);
    expect(passing.stdout).toContain("does not balance");
    const stashed = path.join(stashDir, encodeURIComponent(keyOf(script)));
    expect(existsSync(stashed)).toBe(false);

    // The refusal is named in the payload beside a pass: same fields a read-only `.ci/`
    // produces (a degraded cache, never a verdict), and the repair is to the file.
    const reported: Report = JSON.parse(run(["--json"], { GATE_HASHES_FILE: manifest }).stdout);
    expect(reported.gate).toBe("pass");
    expect(reported.stash?.stashed).toBe(0);
    expect(reported.warning).toContain("kept out of the stash");
    expect(reported.warning).toContain(keyOf(script));
    expect(reported.cause).toContain("not whole");
    expect(reported.cause).toContain("writing to");

    // The positive control: a whole variant of the same pin stashes normally, so the
    // refusal is the balance check and not some side effect of the re-pin.
    writeFileSync(script, "export function half() {\n  const open = (`x`);\n}\n");
    expect(run(["--write"], { GATE_HASHES_FILE: manifest }).status).toBe(0);
    expect(run([], { GATE_HASHES_FILE: manifest }).status).toBe(0);
    expect(readFileSync(stashed, "utf8")).toContain("export function half()");
    expect(dir).toBeDefined();
  });

  it("keeps the text it matched when the usual stash refuses, and still diffs against it", () => {
    const { dir, manifest, script } = fixture();
    // The stash is a convenience, and one that can fail the check is worse than no
    // convenience at all: a full disk, a read-only `.ci/`, or anything else that stops the
    // write would turn a *matching* tree into a non-zero exit — and the exit code is the
    // whole contract, read by `ci.mjs`'s drift stage and by the collect-apply job that gates
    // a commit on it. Pointing the stash at a file is how the write is made to fail.
    const notADirectory = path.join(dir, "not-a-directory");
    writeFileSync(notADirectory, "");
    const env = { GATE_HASHES_FILE: manifest, GATE_CONTENT_DIR: notADirectory };

    const passing = run([], env);
    expect(passing.status).toBe(0);
    expect(passing.stdout).toContain("all match");
    // Reported rather than swallowed: the cache quietly working less well is how a reader
    // comes to trust a diff that has stopped appearing.
    expect(passing.stdout).toContain("could not be stashed in the usual place");
    expect(passing.stdout).toContain("kept at");

    // …and *named* in the payload rather than left for a consumer to infer from a missing
    // `stash` key: `ci.mjs` reads this field and puts it on the run page as a warning on a
    // stage that passed, which is where a degraded diff cache has to be visible.
    const reported: Report = JSON.parse(run(["--json"], env).stdout);
    expect(reported.gate).toBe("pass");
    // A write that failed is not a diff that was lost: the text is on hand, one directory
    // over, and the payload says both — the stash *and* the warning — because the next
    // drift reads fine and the cache is still not where it belongs.
    const kept = path.join(fallbackDir, encodeURIComponent(keyOf(script)));
    expect(reported.stash?.fallback).toBe(fallbackDir);
    expect(readFileSync(kept, "utf8")).toBe("export const alpha = 1;\n");
    expect(reported.warning).toContain("could not be stashed in the usual place");
    expect(reported.warning).toContain("which the OS may clear");
    // The reason travels beside it, because "could not be stashed" narrows nothing on its
    // own: the OS refusal and the directory it refused are what decide whether this is a
    // full disk, a read-only `.ci/`, or a `GATE_CONTENT_DIR` pointed at a file. The `mkdir`
    // error names what it refused here; `ENOSPC` names no path at all, which is why the
    // directory is published with it either way.
    expect(reported.cause).toContain("EEXIST");
    expect(reported.cause).toContain("writing to");
    // …and the log says it too, on its own line under the note, so an operator reading the
    // job log does not have to reach for `--json` to learn what went wrong.
    expect(passing.stdout).toContain("cause: EEXIST");

    // The point of keeping it: the loosening is still read as the line that changed. A
    // refused write on the run that matched is exactly when the text is in hand and will
    // not be again, so spending it there would have cost this diff.
    writeFileSync(script, "export const alpha = 2;\n");
    const drifted = run([], env);
    expect(drifted.status).toBe(1);
    expect(drifted.stdout).toContain("CHANGED");
    expect(drifted.stdout).toContain("-export const alpha = 1;");
    expect(drifted.stdout).toContain("+export const alpha = 2;");
    expect(drifted.stdout).not.toContain("have no pinned copy on hand");
    // And the copy behind that diff is the fallback's, untouched by the failed check: the
    // usual directory was never writable, so the text exists in exactly one place — and the
    // loosened text the failed check just read must not have overwritten it.
    expect(readFileSync(kept, "utf8")).toBe("export const alpha = 1;\n");
  });

  it("reads a copy back from the fallback when the usual stash holds none", () => {
    const { dir, manifest, script } = fixture();
    const ownFallback = path.join(dir, "fallback");
    mkdirSync(ownFallback, { recursive: true });
    // The fallback written by hand, because that is the state this has to read: the usual
    // directory has nothing (it was never written, or was emptied by a cleanup), and the
    // text that matches the pin is elsewhere. It is offered to the diff lookup by the same
    // search that reads the usual place — no flag says "look here" — so this pins the read
    // side of the fallback, which is what makes keeping the text worth anything.
    writeFileSync(
      path.join(ownFallback, encodeURIComponent(keyOf(path.join(dir, "coverage-alpha.mjs")))),
      "export const alpha = 1;\n",
    );
    writeFileSync(script, "export const alpha = 2;\n");
    const env = { GATE_HASHES_FILE: manifest, GATE_CONTENT_FALLBACK_DIR: ownFallback };

    const { status, report } = check(manifest, env);

    expect(status).toBe(1);
    expect(report.findings[0].diff).toContain("-export const alpha = 1;");
    expect(report.findings[0].diff).toContain("+export const alpha = 2;");
  });

  it("reports the loss, with both refusals, when nowhere can be written", () => {
    const { dir, manifest, script } = fixture();
    // Both places refused — a read-only project *and* a temporary directory that cannot be
    // created. Then, and only then, is the diff genuinely spent, and the payload says so
    // with no `stash` at all; the cause names both refusals, because "where should it have
    // gone" is the first question a reader has of a fallback that also failed.
    const notADirectory = path.join(dir, "not-a-directory");
    const alsoNotADirectory = path.join(dir, "also-not-a-directory");
    writeFileSync(notADirectory, "");
    writeFileSync(alsoNotADirectory, "");
    const env = {
      GATE_HASHES_FILE: manifest,
      GATE_CONTENT_DIR: notADirectory,
      GATE_CONTENT_FALLBACK_DIR: alsoNotADirectory,
    };

    const passing = run([], env);
    expect(passing.status).toBe(0);
    expect(passing.stdout).toContain("all match");
    expect(passing.stdout).toContain("the matched text could not be stashed");

    const reported: Report = JSON.parse(run(["--json"], env).stdout);
    expect(reported.warning).toBe("the matched text could not be stashed — the next drift will show hashes only");
    expect(reported.stash).toBeUndefined();
    expect(reported.cause?.match(/writing to/g)).toHaveLength(2);

    // And what the alarm is *for* still answers: a loosened file is a failed check with the
    // hashes and no diff, never a crash and never a pass.
    writeFileSync(script, "export const alpha = 2;\n");
    const drifted = run([], env);
    expect(drifted.status).toBe(1);
    expect(drifted.stdout).toContain("CHANGED");
    expect(drifted.stdout).toContain("have no pinned copy on hand");
  });

  it("keeps the fallback outside the project, in the temporary directory", () => {
    // Without an override the fallback is the OS temporary directory, because the reason
    // the usual stash refused (a read-only `.ci/`, a runner workspace) would refuse a
    // second path inside the project just as firmly — and it is named per project root, so
    // two checkouts on one machine do not take turns rewriting each other's index.
    const saved = process.env.GATE_CONTENT_FALLBACK_DIR;
    delete process.env.GATE_CONTENT_FALLBACK_DIR;
    try {
      const dir = fallbackContentDir();
      expect(path.relative(tmpdir(), dir).startsWith("..")).toBe(false);
      expect(path.relative(projectRoot, dir).startsWith("..")).toBe(true);
      expect(dir).toContain(path.basename(path.resolve(projectRoot)));
    } finally {
      if (saved !== undefined) process.env.GATE_CONTENT_FALLBACK_DIR = saved;
    }
  });

  it("names the stash it wrote instead of warning about one it lost", () => {
    const { manifest } = fixture();

    const { status, report } = check(manifest);

    expect(status).toBe(0);
    // The other half of the contract: a consumer can tell a maintained diff cache from a
    // degraded one by which of the two fields is there, and never by a sentence in the log.
    expect(report.stash).toMatchObject({ stashed: expect.any(Number) });
    // A healthy run wrote where it belongs, so there is nothing to report about *where*.
    expect(report.stash?.fallback).toBeUndefined();
    expect(report.warning).toBeUndefined();
    // A healthy run has nothing to explain either: a `cause` without a `warning` would be a
    // reason for a loss nobody reported.
    expect(report.cause).toBeUndefined();
  });
});

/**
 * The pin's state as one line: what drifted, what a re-pin would record, and whether the
 * diff cache can still read the next drift.
 *
 * The cases here pin the three parts of that sentence separately, because each answers a
 * different question and each can be wrong on its own: a status that named the drift but not
 * what could be recorded sends a reader to the whole-tree command for nothing, one that
 * counted the cache by the wrong total would be wrong only once a file is unpinned or gone,
 * and one that *wrote* while reporting would answer "the cache is healthy" about a cache it
 * had just filled. The last is the one worth a case of its own: `--status` is a reading, and
 * a reading that changes what it reads is not a check but a repair nobody asked for.
 */
describe("the pin's status", () => {
  it("answers in one line, with the count and nothing to record", () => {
    const { manifest } = fixture();
    check(manifest);

    const { status, stdout } = runStatus(manifest);

    expect(status).toBe(0);
    // One line, and the whole answer in it — the shape is the point of the command, and a
    // status that grew a second line would be the check again with a different head.
    expect(stdout.trim().split("\n")).toHaveLength(1);
    expect(stdout).toContain("1 gate file(s) pinned in");
    expect(stdout).toContain("all match");
    expect(stdout).toContain("nothing for a re-pin to record");
    expect(stdout).toContain("the diff cache holds all 1 matched copies");
  });

  it("names the drift, what a re-pin would record, and what it would not", () => {
    const { manifest, alpha, beta } = pairFixture();
    // A passing check first, so the cache holds both copies — and then one of them is dropped
    // by hand, which is the half-full state the count exists to describe: the file the diff
    // survives for and the file whose next drift will be two hex prefixes.
    check(manifest);
    rmSync(path.join(stashDir, encodeURIComponent(keyOf(beta))), { force: true });
    // Two findings of different kinds, which is where a single number would lie: alpha is a
    // file a targeted re-pin could record, beta is a pin only the whole-tree command drops.
    writeFileSync(alpha, "export const alpha = 1;\n// loosened\n");
    rmSync(beta);

    const { status, stdout } = runStatus(manifest);

    expect(status).toBe(1);
    expect(stdout.trim().split("\n")).toHaveLength(1);
    expect(stdout).toContain("2 pinned and 1 watched in");
    expect(stdout).toContain(`${keyOf(alpha)} (changed)`);
    expect(stdout).toContain(`${keyOf(beta)} (gone)`);
    // The distinction the check cannot make and this command exists to make: a re-pin would
    // record the loosened file and *not* the deleted one.
    expect(stdout).toContain("a targeted re-pin records 1 of them");
    // …and the cache, counted against the *pin* — two files, one readable copy between them.
    expect(stdout).toContain("the diff cache holds 1 of 2 matched copies");
    expect(stdout).toContain("1 with no copy on hand and so no diff when they move");

    const reported: Report = JSON.parse(run(["--status", "--json"], { GATE_HASHES_FILE: manifest }).stdout);
    expect(reported.mode).toBe("status");
    expect(reported.pinned).toBe(2);
    expect(reported.checked).toBe(1);
    expect(reported.recordable).toEqual([keyOf(alpha)]);
    // The payload carries the cache and the recordable set as fields, so a script reads them
    // instead of parsing the sentence — and the sentence is what a person reads.
    expect(reported.cache).toMatchObject({ fresh: expect.any(Number), missing: expect.any(Number) });
  });

  it("says the cache is cold rather than quietly warming it", () => {
    const { manifest } = fixture();
    // A key the cache has never held, in a directory that is not even created: the state a
    // person is in before their first passing check, and the one a status command is most
    // tempted to fix on the way past.
    const cold = path.join(caseDir(), "never-written");
    const env = { GATE_HASHES_FILE: manifest, GATE_CONTENT_DIR: cold, GATE_CONTENT_FALLBACK_DIR: cold };

    const first = runStatus(manifest, env);
    expect(first.stdout).toContain("the diff cache is cold");
    // The property the whole mode rests on: asking did not fill it. A status that stashed on
    // the way past would have answered the second question with what the first one wrote.
    const second = runStatus(manifest, env);
    expect(second.stdout).toContain("the diff cache is cold");
    expect(existsSync(path.join(cold, "index.json"))).toBe(false);
  });

  it("counts a copy kept in the fallback as kept, and says where", () => {
    const { manifest } = fixture();
    // A pass whose usual stash refused, which is the degraded state the report has to be able
    // to tell apart from a cold one: the diff still reads, from somewhere the OS may clear.
    const notADirectory = path.join(caseDir(), "not-a-directory");
    writeFileSync(notADirectory, "");
    const ownFallback = path.join(caseDir(), "fallback");
    const env = {
      GATE_HASHES_FILE: manifest,
      GATE_CONTENT_DIR: notADirectory,
      GATE_CONTENT_FALLBACK_DIR: ownFallback,
    };
    expect(run([], env).status).toBe(0);

    const { status, stdout } = runStatus(manifest, env);

    expect(status).toBe(0);
    expect(stdout).toContain("the diff cache holds all 1 matched copies");
    expect(stdout).toContain(`, all of them in the temporary fallback at ${ownFallback}`);
  });

  it("refuses to write while reporting, because that would answer its own question", () => {
    const { manifest, alpha } = pairFixture();
    const before = readFileSync(manifest, "utf8");

    const withWrite = run(["--status", "--write"], { GATE_HASHES_FILE: manifest });
    const withTarget = run(["--status", keyOf(alpha)], { GATE_HASHES_FILE: manifest });

    expect(withWrite.status).toBe(2);
    expect(withWrite.stdout).toContain("does not change it");
    expect(withTarget.status).toBe(2);
    expect(withTarget.stdout).toContain("does not change it");
    expect(readFileSync(manifest, "utf8")).toBe(before);
  });
});

/**
 * Where the watch rules are *not* written a second time.
 *
 * `DEFAULT_WATCHES` in `.freebuff/gate-drift.mjs` is the one declaration of what the alarm
 * covers, and the two cases below hold the committed manifest's recorded copy to it. The
 * rules are deliberately not spelled out here: this file used to carry a byte-for-byte copy,
 * and the time the manifest and the script disagreed it was that copy which had been widened
 * alongside the manifest while the declaration had not — so `npm run gates:pin`, which reads
 * the declaration, would have rendered the narrower list, dropped two files from the pin and
 * failed this comparison as though the pinner had done something wrong. Importing the
 * declaration is what makes that impossible rather than merely unlikely; the alarm refuses a
 * manifest that records anything else, so all three readings — the default, the record and
 * what `--write` renders — come from one list.
 *
 * The *policy* is still what gets pinned rather than the resolved paths. The rules are
 * patterns, so a typo — or a family narrowed wholesale — would silently shrink the pin
 * while every remaining hash still matched — the `.github/workflows` rule being the one
 * that has to name a directory two levels down, and the one whose whole point is that a
 * step deleted from it cancels stages that could never notice — which is the same failure
 * `src/test/coverage-gates.test.ts` guards for the coverage scopes one level in. The
 * *membership* is deliberately left to the manifest and the freshness check below: a new
 * gate file in a family should demand the one command that re-pins it, not an edit to
 * the declaration, or the rules would be the thing everyone resents rather than the thing
 * that catches a narrowing.
 *
 * This declaration has a second consumer, and it is the reason a widened rule is not merely
 * recorded but *enforced* on the next run: `.freebuff/ci.mjs` gives its drift stage these
 * rules as its `inputs`, so a family watched here is behind that stage's cache key because
 * it is the rule rather than because a list beside the runner agreed. What that buys is
 * checked where the runner is — see the case in `src/test/ci-runner.test.ts` that holds the
 * stage's inputs to every file `pin` resolves — because the claim is about the pair.
 */

/**
 * The headline files the pin must always reach, whatever the rules are edited to.
 *
 * A superset check rather than an exact set: these are the files the alarm exists for —
 * the runner, the two checks and their lock, the configs that decide what the suite
 * measures, what the client bundle is built from, what the stylesheet pipeline emits and
 * what the deployed worker is, the workflows that run it — and a rule edit that dropped one
 * of them while keeping the rules list plausible would fail here.
 */
const CORE = [
  ".freebuff/build-contents.mjs",
  ".freebuff/ci.mjs",
  ".freebuff/gate-drift.mjs",
  ".freebuff/lint-baseline.mjs",
  ".freebuff/mutation-coverage.mjs",
  ".freebuff/mutation-guards.mjs",
  ".freebuff/mutation-lock.mjs",
  ".freebuff/nightly-report.mjs",
  ".freebuff/preview-preflight.mjs",
  ".freebuff/redact.mjs",
  ".freebuff/runbook-contents.mjs",
  ".freebuff/stage-order.json",
  ".freebuff/whole-write.mjs",
  ".github/workflows/ci.yml",
  ".github/workflows/collect-apply.yml",
  ".github/workflows/nightly.yml",
  "eslint.config.mjs",
  "next.config.mjs",
  "postcss.config.mjs",
  "tsconfig.json",
  "vite.config.ts",
  "vitest.config.ts",
  "vitest.mutation.config.ts",
  "wrangler.jsonc",
];

describe("the committed gate manifest", () => {
  it("records the whole gate surface as watch rules, and no dead rule", async () => {
    const committed = (await import(pathToFileURL(manifestPath()).href)) as unknown as {
      algorithm: string;
      watches: { dir: string; pattern: string }[];
      files: Record<string, string>;
    };

    expect(committed.watches).toEqual(DEFAULT_WATCHES);
    expect(committed.algorithm).toBe("sha1");
    for (const hash of Object.values(committed.files)) expect(hash).toMatch(/^[0-9a-f]{40}$/);

    // Every recorded pin is a file, and every rule reaches at least one of them: a rule
    // that has stopped matching is a family that quietly left the alarm.
    expect(Object.keys(committed.files)).toEqual(expect.arrayContaining(CORE));
    for (const rule of DEFAULT_WATCHES) {
      expect(Object.keys(pin([manifestPath()], [rule])).length, `${rule.pattern} matches nothing`).toBeGreaterThan(0);
    }
  });

  it("watches exactly the build configs the client-env guard reads", () => {
    // The pin and the suite are two halves of one promise about these files: the guard
    // reads each of them for a value the bundler would inline into a client bundle, and the
    // pin is what catches a change that guard's policy does not describe — a literal in a
    // `define:` table, an image host added to `next.config.mjs`. So neither list may grow
    // alone: a third config the guard starts reading, or a rule that reaches past this pair,
    // fails here instead of on a reviewer who had no reason to open either file.
    const claimant = DEFAULT_WATCHES.find((rule) =>
      new RegExp(rule.pattern).test(CLIENT_BUILD_CONFIGS[0]),
    ) as { dir: string; pattern: string } | undefined;
    expect(claimant, `no watch rule claims ${CLIENT_BUILD_CONFIGS[0]}`).toBeDefined();
    const rule = claimant as { dir: string; pattern: string };
    // One family, or the two halves could be pinned by rules that disagree about it.
    for (const config of CLIENT_BUILD_CONFIGS) {
      expect(new RegExp(rule.pattern).test(config), `${config} is not in the rule's family`).toBe(true);
    }

    expect(Object.keys(pin([manifestPath()], [rule])).sort()).toEqual(
      [...CLIENT_BUILD_CONFIGS].sort(),
    );
  });

  it("watches the stylesheet pipeline and the deployed worker, and leaves the drizzle pointer out on purpose", () => {
    // Two files pinned for the same reason the client configs are — no checker reads either —
    // and one left out, which is the half a documented exception usually loses. The suite
    // parses `globals.css` and says in `src/test/globals-layer.test.ts` that it cannot see the
    // *generated* stylesheet, so the config that decides whether Tailwind emits anything is
    // invisible to it; `wrangler.jsonc` decides what the deployed worker is, and is the source
    // `worker-configuration.d.ts` is regenerated from for `tsc` to read as `Env`. Both are one
    // level down in `.`, which is what a rule reads, so the rule that claims one claims the
    // other and nothing else.
    const shipping = ["postcss.config.mjs", "wrangler.jsonc"];
    const claimant = DEFAULT_WATCHES.find((rule) =>
      new RegExp(rule.pattern).test(shipping[0]),
    ) as { dir: string; pattern: string } | undefined;
    expect(claimant, `no watch rule claims ${shipping[0]}`).toBeDefined();
    const rule = claimant as { dir: string; pattern: string };
    for (const config of shipping) {
      expect(new RegExp(rule.pattern).test(config), `${config} is not in the rule's family`).toBe(true);
    }
    expect(Object.keys(pin([manifestPath()], [rule])).sort()).toEqual([...shipping].sort());

    // And the exception is held rather than only written down: `drizzle.config.ts` stays
    // outside because it names a path for a tool whose output is reviewed as ordinary source,
    // so a rule that quietly began matching it would pin a file the declaration's own reason
    // says is not there. Promoting it is then an edit to this case *and* to the declaration,
    // which is the review that decision deserves.
    expect(DEFAULT_WATCHES.some((r) => new RegExp(r.pattern).test("drizzle.config.ts"))).toBe(false);
  });

  it("scans by the one declaration, and refuses a manifest that records any other rules", async () => {
    // The other half of the single source: it is not enough for the two lists to happen to
    // agree, since that is exactly the state a widening of either one breaks. The alarm
    // takes its rules from the declaration and refuses its own manifest when the record
    // differs, so a hand-widened manifest cannot widen the pin and a widened declaration is
    // not silently undone by the next re-pin. `GATE_HASHES_FILE` is what makes a fixture
    // manifest a *whole other* pin, rules and all, which is why it is cleared for these two
    // readings — a substituted manifest is the one case with rules of its own.
    const seam = process.env.GATE_HASHES_FILE;
    delete process.env.GATE_HASHES_FILE;
    try {
      const own = await readManifest(manifestPath());
      expect(own.problem).toBeNull();
      expect(own.watches).toEqual(DEFAULT_WATCHES);

      const dir = caseDir();
      writeFileSync(path.join(dir, "coverage-alpha.mjs"), "export const alpha = 1;\n");
      const divergent = path.join(dir, "gate-hashes.mjs");
      // Well-formed rules that do match real files — so nothing but the disagreement with
      // the declaration is wrong with this manifest — and deliberately a *different* set:
      // a narrowing the pin would otherwise obey.
      writeFileSync(
        divergent,
        renderManifest({
          algorithm: "sha1",
          watches: [{ dir: ".freebuff", pattern: "^coverage-floor\\.mjs$" }],
          files: {},
        }),
      );

      const refused = await readManifest(divergent);
      expect(refused.problem).toContain("watch rules that are not the declared ones");
      // And the declaration is what it would scan by and record anyway, so the repair
      // `--write` writes is the declared list rather than the recorded one.
      expect(refused.watches).toEqual(DEFAULT_WATCHES);
    } finally {
      if (seam === undefined) delete process.env.GATE_HASHES_FILE;
      else process.env.GATE_HASHES_FILE = seam;
    }
  });

  it("matches the gate machinery on disk, and is exactly what --write would produce", async () => {
    // No seam: the real manifest, the real tree. This is the ratchet — a hand edit to a
    // gate script, a runner, a vitest config, or a file added to a watched family without
    // a re-pin, fails here before the drift stage has to say it in CI.
    const result = run(["--json"]);
    expect(result.status, `gate-drift: ${result.stdout}${result.stderr}`).toBe(0);
    const report = JSON.parse(result.stdout) as Report;
    expect(report.manifest).toBe(MANIFEST_FILE);
    expect(report.findings).toEqual([]);

    const committed = (await import(pathToFileURL(manifestPath()).href)) as unknown as {
      algorithm: string;
      watches: { dir: string; pattern: string }[];
      files: Record<string, string>;
    };
    // `checked` is what the rules resolve to *now*, so it equalling what is recorded is
    // the freshness statement the CLI makes — the same one the drift stage enforces.
    expect(report.checked).toBe(Object.keys(committed.files).length);
    expect(readFileSync(manifestPath(), "utf8")).toBe(
      renderManifest({
        algorithm: committed.algorithm,
        watches: committed.watches,
        files: committed.files,
      }),
    );
  });
});

// Seven sequential spawns of the real scaffold — and the apply-check case adds five git
// spawns on top — against a scratch tree copied fresh per case. The default 5s test timeout
// assumes a quiet box; this checkout is routinely shared (a concurrent sweep's load once
// pushed the re-draft case past it at 5270 ms), and a case that holds a fact per spawn, not a
// speed, should not flake on the machine's worst day. The budget is the describe's, so each
// case inherits it and the re-draft's three-spawn sequence fits without a per-case number.
describe("the sweep scaffold", { timeout: 60_000 }, () => {
  /** The scaffold, not the alarm: `SCRIPT` above is gate-drift.mjs, this describe's subject is not. */
  const SCAFFOLD = path.join(projectRoot, ".freebuff", "scaffold-sweep.mjs");

  /** Run the scaffold over a scratch tree, `--json`, its report and exit code beside the stderr. */
  function scaffold(root: string, args: string[]): {
    status: number | null;
    report: {
      gate: string;
      error?: string;
      name?: string;
      stages?: number;
      created?: string[];
      edited?: string[];
      suitePatch?: string;
      checklist?: string[];
      draftOnly?: boolean;
    };
    stderr: string;
  } {
    const result = spawnSync(process.execPath, [SCAFFOLD, ...args], {
      cwd: projectRoot,
      encoding: "utf8",
      env: { ...process.env, SCAFFOLD_ROOT: root },
    });
    if (result.error) throw result.error;
    return {
      status: result.status,
      report: JSON.parse(result.stdout || "{}"),
      stderr: result.stderr ?? "",
    };
  }

  /**
   * A scratch tree with everything the scaffold reads and edits: the import closure of the
   * runner (so its `--stages` audit and `--stages=write` answer over the copies), the watch
   * rule files the audit counts, the template sweep and the module it speaks, the other
   * four stage-order files whose claims the audit holds, and the drift suite whose
   * tail-zone claim and scaffold e2e case the `--tests` draft edits.
   */
  function scratchTree(): string {
    const dir = mkdtempSync(path.join(tmpdir(), "scaffold-sweep-"));
    const closure = importClosure(".freebuff/ci.mjs");
    const files = new Set([...closure].map((file) => file.split("\\").join("/")));
    for (const file of [
      ".freebuff/mutation-example.mjs",
      ".freebuff/mutation-vocabulary.mjs",
      ".freebuff/run.md",
      "src/test/ci-runner.test.ts",
      "src/test/gate-drift.test.ts",
      "src/test/ci-runner-tree-editing.test.ts",
      ".github/workflows/nightly.yml",
    ]) {
      files.add(file);
    }
    for (const file of files) {
      const target = path.join(dir, file);
      mkdirSync(path.dirname(target), { recursive: true });
      copyFileSync(path.join(projectRoot, file), target);
    }
    return dir;
  }

  /** Every scratch tree this describe made, so the afterAll below can take them. */
  const made: string[] = [];

  afterAll(() => {
    for (const dir of made) rmSync(dir, { recursive: true, force: true });
  });

  it("onboards a sweep end to end: words, sweep, table entry, pre-pass, renumber", () => {
    const root = scratchTree();
    made.push(root);
    const { status, report } = scaffold(root, ["--name=fifthcase", "--json"]);

    expect(status).toBe(0);
    expect(report.gate).toBe("pass");
    expect(report.name).toBe("mutation-fifthcase");
    expect(report.stages).toBe(12);
    // The scaffold reports each edited path in the platform's own spelling, so
    // normalize to forward slashes before comparing — the same normalization the
    // closure walk above does — and the expectation reads identically on every OS.
    const edited = (report.edited ?? []).map((file) => file.split("\\").join("/"));
    expect(edited).toEqual(
      expect.arrayContaining([".freebuff/mutation-vocabulary.mjs", ".freebuff/gate-drift.mjs", ".freebuff/ci.mjs"]),
    );
    // The generated sweep answers both of its modes out of the tree it was written into.
    const sweep = spawnSync(process.execPath, [path.join(root, ".freebuff", "mutation-fifthcase.mjs"), "--json"], {
      encoding: "utf8",
    });
    const payload = JSON.parse(sweep.stdout) as { gate: string; checked: number; survivors: unknown[] };
    expect(payload.gate).toBe("pass");
    expect(payload.checked).toBe(1);
    expect(payload.survivors).toEqual([]);
  });

  it("refuses a drifted template instead of mangling it, and restores the tree", () => {
    const root = scratchTree();
    made.push(root);
    // A capital the tokens do not cover: the substitution is case-sensitive, so "Fourth" in
    // the template is template text the scaffold does not rename — and a generated sweep
    // carrying the fourth sweep's name in its own prose is exactly the mangling the leftover
    // check refuses, naming the line rather than generating through it.
    const template = path.join(root, ".freebuff", "mutation-example.mjs");
    writeFileSync(template, readFileSync(template, "utf8").replace("fourth sweep", "Fourth sweep"), "utf8");

    const { status, report } = scaffold(root, ["--name=fifthcase", "--json"]);

    expect(status).toBe(1);
    expect(report.gate).toBe("fail");
    expect(report.error).toContain("tokens");
    // The refusal leaves nothing behind: the new sweep is gone, and every edited byte is back.
    expect(existsSync(path.join(root, ".freebuff", "mutation-fifthcase.mjs"))).toBe(false);
    expect(readFileSync(path.join(root, ".freebuff", "mutation-vocabulary.mjs"), "utf8")).not.toContain(
      "FIFTHCASE_SURVIVOR_WORDS",
    );
  });

  it("refuses usage and names the contract", () => {
    // No name, no tree: usage is refused before any precondition is read or any spawn happens,
    // so the case needs neither a scratch tree nor the alarm's pin — a refusal that needed one
    // would be a refusal nobody could read before they had a tree to fix.
    const { status, report } = scaffold(projectRoot, ["--json"]);

    expect(status).toBe(2);
    expect(report.gate).toBe("fail");
    expect(report.error).toContain("usage:");
  });

  // The claims the cases derive rather than quote: the alarm's tail-zone sentence over the
  // table as it stands and over the table with the case's own sweep added — derived the
  // way the alarm derives it (the bent-lint case counts lint as a fourth editor, and the
  // new stage lands right after the example) — so the cases survive the onboardings they
  // ride along with instead of quoting a generation's prose.
  const editorCount = STAGE_TABLE.filter((stage) => stage.editsTree !== undefined).length + 1;
  const tableOrder = STAGE_TABLE.map((stage) => stage.name);
  const claimOver = (order: string[]) =>
    `one of the last ${editorCount} (${order.slice(order.length - editorCount).join(", ")})`;
  const orderWith = (candidate: string) => {
    const at = tableOrder.indexOf("mutation-example");
    return [...tableOrder.slice(0, at + 1), `mutation-${candidate}`, ...tableOrder.slice(at + 1)];
  };
  const currentTailClaim = claimOver(tableOrder);
  const freshName =
    ["probe", "probe2", "probe3"].find((candidate) => !tableOrder.includes(`mutation-${candidate}`)) ?? "probe";
  const freshTailClaim = claimOver(orderWith(freshName));

  it("drafts the suite extensions as a reviewed patch instead of editing the suites", () => {
    const root = scratchTree();
    made.push(root);
    const { status, report } = scaffold(root, [`--name=${freshName}`, "--tests", "--json"]);

    expect(status).toBe(0);
    expect(report.gate).toBe("pass");
    expect(report.name).toBe(`mutation-${freshName}`);
    expect(report.stages).toBe(STAGE_TABLE.length + 1);
    // The suites stay untouched: the patch is the artifact, the operator applies it, and
    // the checklist says so instead of pointing at edits the scaffold never made.
    expect(report.suitePatch).toBe([".freebuff", `scaffold-tests-${freshName}.patch`].join(path.sep));
    expect(report.checklist?.[0]).toContain("review and apply");
    expect(report.checklist?.[0]).toContain(`scaffold-tests-${freshName}.patch`);
    const runnerSuite = readFileSync(path.join(root, "src", "test", "ci-runner.test.ts"), "utf8");
    const driftSuite = readFileSync(path.join(root, "src", "test", "gate-drift.test.ts"), "utf8");
    expect(runnerSuite).not.toContain(`"mutation-example", "mutation-${freshName}"]`);
    expect(driftSuite).toContain(`the lint stage edits the tree, so it has to be ${currentTailClaim}`);
    // The patch carries every claim: the wiring case, the count literals, the tail-zone
    // claim derived the way the bent table derives it, and the not-run lines (three
    // assertions, a minus and a plus each).
    const patchText = readFileSync(path.join(root, ".freebuff", `scaffold-tests-${freshName}.patch`), "utf8");
    expect(patchText).toContain("--- a/src/test/ci-runner.test.ts");
    expect(patchText).toContain("--- a/src/test/gate-drift.test.ts");
    expect(patchText).toContain(`"mutation-example", "mutation-${freshName}"`);
    if (freshTailClaim === currentTailClaim) {
      // A stage that lands outside the tail zone leaves the sentence standing: the patch
      // holds no tail hunk, and the suite's claim already names the tail it produces.
      expect(patchText).not.toContain("the lint stage edits the tree");
    } else {
      expect(patchText).toContain(
        `+          "the lint stage edits the tree, so it has to be ${freshTailClaim}",`,
      );
    }
    expect(patchText.split("not run (nothing they read changed)").length - 1).toBe(6);
  });

  it("drafts a patch that passes git apply --check in a throwaway repo", () => {
    const root = scratchTree();
    made.push(root);
    const { status } = scaffold(root, [`--name=${freshName}`, "--tests", "--json"]);
    expect(status).toBe(0);

    // The patch is only as good as its ability to apply: a renderer whose hunks drift
    // from the bytes the suites actually hold would pass every rule verify and still
    // refuse at the operator's first `git apply --check`. So the draft is checked the
    // way the operator checks it — in a throwaway repo whose base commit is the
    // untouched suites, then applied and read back. autocrlf is pinned off so the rows
    // are compared byte-for-byte, the way the drafted text was verified.
    const repo = mkdtempSync(path.join(tmpdir(), "scaffold-applycheck-"));
    made.push(repo);
    const git = (args: string[]) => {
      const result = spawnSync("git", ["-c", "core.autocrlf=false", ...args], {
        cwd: repo,
        encoding: "utf8",
      });
      if (result.error) throw result.error;
      return { status: result.status, stderr: result.stderr ?? "" };
    };
    for (const file of ["src/test/ci-runner.test.ts", "src/test/gate-drift.test.ts"]) {
      mkdirSync(path.dirname(path.join(repo, file)), { recursive: true });
      copyFileSync(path.join(root, file), path.join(repo, file));
    }
    copyFileSync(
      path.join(root, ".freebuff", `scaffold-tests-${freshName}.patch`),
      path.join(repo, `scaffold-tests-${freshName}.patch`),
    );
    expect(git(["init", "-q"]).status).toBe(0);
    expect(git(["add", "-A"]).status).toBe(0);
    expect(
      git(["-c", "user.email=scaffold@test", "-c", "user.name=scaffold", "commit", "-qm", "the suites as the scaffold found them"])
        .status,
    ).toBe(0);
    const check = git(["apply", "--check", `scaffold-tests-${freshName}.patch`]);
    expect(check.stderr).toBe("");
    expect(check.status).toBe(0);
    expect(git(["apply", `scaffold-tests-${freshName}.patch`]).status).toBe(0);

    // The applied text is the edit the rules verified: the new stage rides the wiring
    // for-line and the single-line tail array, the e2e case carries the fresh name, and
    // a stage that lands inside the tail zone leaves the new claim standing.
    const appliedRunner = readFileSync(path.join(repo, "src", "test", "ci-runner.test.ts"), "utf8");
    const appliedDrift = readFileSync(path.join(repo, "src", "test", "gate-drift.test.ts"), "utf8");
    expect(appliedRunner).toContain(`"mutation-example", "mutation-${freshName}"`);
    expect(appliedDrift).toContain(`--name=${freshName}case`);
    if (freshTailClaim !== currentTailClaim) {
      expect(appliedDrift).toContain(`has to be ${freshTailClaim}`);
    }
  });

  it("drafts the suite extensions again on an already-onboarded tree instead of refusing", () => {
    const root = scratchTree();
    made.push(root);
    expect(scaffold(root, [`--name=${freshName}`, "--json"]).status).toBe(0);
    // The once-only rule still holds without --tests ...
    const again = scaffold(root, [`--name=${freshName}`, "--json"]);
    expect(again.status).toBe(1);
    expect(again.report.error).toContain("already onboarded");
    // ... but --tests on an onboarded tree is the re-draft: nothing left to build, suites
    // possibly still waiting for their extensions, and a fresh patch is cheaper than
    // remembering the command that wrote the first one.
    const { status, report } = scaffold(root, [`--name=${freshName}`, "--tests", "--json"]);

    expect(status).toBe(0);
    expect(report.gate).toBe("pass");
    expect(report.draftOnly).toBe(true);
    expect(report.suitePatch).toBe([".freebuff", `scaffold-tests-${freshName}.patch`].join(path.sep));
    const patchText = readFileSync(path.join(root, ".freebuff", `scaffold-tests-${freshName}.patch`), "utf8");
    if (freshTailClaim !== currentTailClaim) {
      expect(patchText).toContain(
        `+          "the lint stage edits the tree, so it has to be ${freshTailClaim}",`,
      );
    }
    expect(patchText).toContain("--- a/src/test/gate-drift.test.ts");
  });

  it("refuses to draft a suite patch whose claims the suites no longer make", () => {
    const root = scratchTree();
    made.push(root);
    // A suite that has already reworded the tail-zone sentence is a suite the draft cannot
    // pair with: the rule's needle matches nothing, and the refusal names the rule rather
    // than writing a patch that reds the suites. The reworded line survives the rollback —
    // the scaffold never owned it — and no patch file is written.
    const driftSuite = path.join(root, "src", "test", "gate-drift.test.ts");
    writeFileSync(
      driftSuite,
      readFileSync(driftSuite, "utf8").replace(
        `the lint stage edits the tree, so it has to be ${currentTailClaim}`,
        "the lint stage edits the tree, so it lands among the last four",
      ),
      "utf8",
    );
    const { status, report } = scaffold(root, [`--name=${freshName}`, "--tests", "--json"]);

    expect(status).toBe(1);
    expect(report.gate).toBe("fail");
    expect(report.error).toContain("tail-zone claim");
    expect(readFileSync(driftSuite, "utf8")).toContain("lands among the last four");
    expect(existsSync(path.join(root, ".freebuff", `scaffold-tests-${freshName}.patch`))).toBe(false);
  });
});
